'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const Connect=require('../public/connect22.js'),Guide=require('../public/guidance22.js');
test('task connections expose known keys and labels only, never paths or absent folders',()=>{const data={guidance:{onboarding:{projects:[{key:'abcd1234',name:'Garden',folder:'/private/folder',taskFolderExists:true},{key:'other',name:'Clock',taskFolderExists:false}]}}};assert.deepEqual(Connect.choices(data),[{key:'abcd1234',name:'Garden'}]);for(const lang of ['en','pt','es']){assert.match(Connect.T[lang].request,/tasks/);assert.match(Connect.T[lang].request,/decisions.md/);assert.doesNotMatch(Connect.T[lang].request,/clipboard|portapapeles|área de transferência/);}});
test('Search again discovers a newly created tasks folder without waiting for the automatic cache',async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'connect22-')),project=path.join(profile,'Garden');fs.mkdirSync(project);const metrics={index:{metadata:new Map([['fake',{privateProjectRoots:[{key:'abcd1234',name:'Garden',folder:project}]}]])}},rules=require('../src/lib/guidance-rules.cjs').createRules(profile,metrics),usage={sessions:[]},board={board:{connected:false}};try{assert.equal((await rules.snapshot(usage,board)).onboarding.projects[0].taskFolderExists,false);fs.mkdirSync(path.join(project,'tasks'));assert.equal((await rules.snapshot(usage,board)).onboarding.projects[0].taskFolderExists,false);rules.invalidate();assert.equal((await rules.snapshot(usage,board)).onboarding.projects[0].taskFolderExists,true);assert.equal(rules.resolveTaskFolder('abcd1234'),path.join(project,'tasks'));assert.throws(()=>rules.resolveTaskFolder('unknown'));}finally{const resolved=path.resolve(profile);assert.ok(resolved.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(resolved).startsWith('connect22-'));fs.rmSync(resolved,{recursive:true,force:true});}});
test('copyable advice names the project, asks how instead of changing settings, and never executes the request',()=>{for(const lang of ['en','pt','es']){const context=Guide.describe({type:'context',values:{percent:76,projectName:'Garden',handoffFile:'handoff.md'}},lang);assert.match(context.copies[1],/Garden/);assert.match(context.copies[1],/handoff.md/);const code=Guide.describe({type:'small-model-code',values:{projectName:'Garden'}},lang);assert.equal(code.copies.length,2);assert.match(code.copies[0],/Garden/);assert.match(code.copies[1],/Do not change|Não mude|No cambies/);const effort=Guide.describe({type:'effort-read',values:{}},lang);assert.equal(effort.copies.length,1);assert.equal(effort.note,null);}});
class Node{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.attributes={};}append(...n){this.children.push(...n);}setAttribute(k,v){this.attributes[k]=v;}removeAttribute(k){delete this.attributes[k];}focus(){}querySelectorAll(tag){return this.children.flatMap(n=>typeof n==='object'?[...(n.tagName===tag?[n]:[]),...n.querySelectorAll(tag)]:[]);}}
test('connection drawer copies creation requests and posts only a known key on explicit connection',async()=>{const copied=[],requests=[],d={documentElement:{lang:'pt'},createElement:t=>new Node(t),getElementById:()=>({click(){}})},root={document:d,navigator:{clipboard:{writeText:async text=>copied.push(text)}},fetch:async(url,init)=>{requests.push({url,body:JSON.parse(init.body)});return {ok:true};},panelDrawer(title,children){root.drawer=children[0];root.title=title;}};const ctx={window:root,AbortController};for(const file of ['copy-session.js','connect22.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public',file),'utf8'),ctx);root.PanelConnect22.open({guidance:{onboarding:{projects:[{key:'abcd1234',name:'Garden',taskFolderExists:true}]}}});assert.equal(root.drawer.querySelectorAll('input').length,0);assert.equal(requests.length,0);const buttons=root.drawer.querySelectorAll('button'),connect=buttons.find(n=>n.dataset.projectKey);await connect.onclick();assert.deepEqual(requests,[{url:'/api/onboarding-connect',body:{projectKey:'abcd1234'}}]);const copy=buttons.find(n=>n.className==='copy-session-button');await copy.onclick();assert.equal(copied[0],Connect.T.pt.request);assert.match(root.drawer.querySelectorAll('p').find(n=>n.className==='copy-session-phrase').textContent,/permitir|permita/);});

const {createServer}=require('../src/panel.cjs');
test('all copy and connection assets are served by the real asset whitelist',async()=>{const server=createServer({demoOnly:true,offline:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{for(const asset of ['/copy-session.js','/copy-session.css','/connect22.js']){const response=await fetch('http://127.0.0.1:'+server.address().port+asset);assert.equal(response.status,200,asset);assert.match(response.headers.get('content-type'),asset.endsWith('.css')?/text\/css/:/javascript/);assert.ok((await response.text()).length>100);}}finally{await new Promise(resolve=>server.close(resolve));}});
