'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),Copy=require('../public/copy-session.js');
class Node{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.attributes={};this.style={};this.hidden=false;this.className='';}append(...nodes){this.children.push(...nodes);for(const n of nodes)n.parent=this;}setAttribute(k,v){this.attributes[k]=v;}removeAttribute(k){delete this.attributes[k];}focus(){this.focused=true;}select(){this.selected=true;}remove(){this.parent.children=this.parent.children.filter(n=>n!==this);}}
function runtime(writeText,execCommand){const doc={body:new Node('body'),createElement:tag=>new Node(tag),createRange:()=>({selectNodeContents(node){this.node=node;}}),execCommand},selection={removeAllRanges(){},addRange(range){this.range=range;}};return {document:doc,navigator:{clipboard:{writeText}},getSelection:()=>selection,selection};}
test('approved paste phrases are persistent and distinguish file edits in EN/PT/ES and Claude/Codex',()=>{
 const expected={en:['Paste it into any Claude Code chat running on your computer. Done.','Paste it into any Claude Code chat running on your computer. If it asks to edit the file, allow it. Done.'],pt:['Cole em qualquer conversa do Claude Code que roda no seu computador. Pronto.','Cole em qualquer conversa do Claude Code que roda no seu computador. Se ela pedir para editar o arquivo, permita. Pronto.'],es:['Pégalo en cualquier conversación de Claude Code que corra en tu ordenador. Listo.','Pégalo en cualquier conversación de Claude Code que corra en tu ordenador. Si pide editar el archivo, permítelo. Listo.']};
 for(const lang of Object.keys(expected))for(const target of ['claude','codex'])for(const writesFile of [false,true]){const phrase=Copy.phrase(lang,target,writesFile),r=runtime(async()=>{}),g=Copy.create({runtime:r,lang,target,label:'Copy',text:'Task',writesFile});assert.equal(phrase,expected[lang][+writesFile].replace('Claude Code',target==='codex'?'Codex':'Claude Code'));assert.equal(g.phrase.textContent,phrase);assert.equal(g.phrase.hidden,false);assert.equal(g.fallback.hidden,true);}
});
test('copying is click-only, language fallback is safe and tool switching updates text and phrase',async()=>{const saved=[],r=runtime(async text=>saved.push(text)),g=Copy.mount(r.document.body,{runtime:r,lang:'pt',label:target=>'Copiar para '+target,text:target=>'Instrucao para '+target,writesFile:true});assert.equal(saved.length,0);assert.equal(r.document.body.children[0],g);await g.button.onclick();assert.deepEqual(saved,['Instrucao para claude']);g.switcher.onclick();assert.equal(g.getTarget(),'codex');assert.equal(g.dataset.target,'codex');assert.equal(g.button.textContent,'Copiar para codex');assert.equal(g.phrase.textContent,Copy.phrase('pt','codex',true));await g.button.onclick();assert.deepEqual(saved,['Instrucao para claude','Instrucao para codex']);assert.equal(Copy.phrase('__proto__'),Copy.phrase('en'));});
test('busy copy snapshots target and instruction; duplicate clicks and switch attempts do not race',async()=>{let finish,seen,calls=0;const r=runtime(text=>{seen=text;calls++;return new Promise(done=>{finish=done;});}),g=Copy.create({runtime:r,lang:'en',text:target=>'Save '+target,onCopied:entry=>{g.copied=entry;}}),first=g.button.onclick();assert.equal(g.button.disabled,true);assert.equal(g.switcher.disabled,true);assert.equal(g.button.attributes['aria-busy'],'true');g.switcher.onclick();assert.equal(g.setTarget('codex'),false);g.setText('A later instruction');await g.button.onclick();assert.equal(calls,1);finish();await first;assert.equal(seen,'Save claude');assert.equal(g.copied.target,'claude');assert.equal(g.copied.text,'Save claude');assert.equal(g.copied.phrase,Copy.phrase('en'));assert.equal(g.button.disabled,false);assert.equal(g.switcher.disabled,false);assert.equal(g.button.attributes['aria-busy'],undefined);});
test('blocked clipboard reveals and selects the exact instruction without dropping the persistent phrase',async()=>{const r=runtime(async()=>{throw Error('denied');}),g=Copy.create({runtime:r,lang:'es',text:'Revisa Garden y espera mi visto bueno.',paste:target=>'Pégalo en la conversación de '+(target==='codex'?'Codex':'Claude Code')+' que abrió esos ayudantes, en Garden. Listo.'});assert.ok(g.phrase.textContent.includes('Garden'));assert.equal(await g.button.onclick(),false);assert.equal(g.fallback.hidden,false);assert.equal(g.fallback.textContent,'Revisa Garden y espera mi visto bueno.');assert.equal(r.selection.range.node,g.fallback);assert.equal(g.button.disabled,false);assert.equal(g.switcher.disabled,false);assert.ok(g.phrase.textContent.includes('Garden'));g.switcher.onclick();assert.ok(g.phrase.textContent.includes('Codex'));assert.equal(g.fallback.hidden,true);});
test('execCommand fallback uses a temporary field and always restores focus and removes it',async()=>{let selectedCommand;const r=runtime(async()=>{throw Error('denied');},name=>{selectedCommand=name;return true;}),old=new Node('button');r.document.activeElement=old;assert.equal(await Copy.copyToClipboard('Text only',r),true);assert.equal(selectedCommand,'copy');assert.equal(r.document.body.children.length,0);assert.equal(old.focused,true);r.document.execCommand=()=>{throw Error('no');};assert.equal(await Copy.copyToClipboard('Still text',r),false);assert.equal(r.document.body.children.length,0);});
test('shared fallback is made visible even when a caller hid it; busy clears after callbacks throw',async()=>{const r=runtime(async()=>{throw Error('denied');}),fallback=new Node('pre'),g=Copy.create({runtime:r,lang:'pt',text:'Tire só a seção marcada.',fallback,onFallback(){fallback.hidden=true;}});await g.button.onclick();assert.equal(fallback.hidden,false);assert.equal(r.selection.range.node,fallback);const success=Copy.create({runtime:runtime(async()=>{}),text:'Status',onCopied(){throw Error('callback');}});await assert.rejects(success.button.onclick(),/callback/);assert.equal(success.button.disabled,false);assert.equal(success.switcher.disabled,false);});
test('primitive performs no network request, file operation or stored preference write',()=>{const source=fs.readFileSync(require.resolve('../public/copy-session.js'),'utf8');assert.doesNotMatch(source,/\bfetch\(|XMLHttpRequest|WebSocket|sendBeacon|EventSource|localStorage|writeFile|require\(/);const css=fs.readFileSync(require.resolve('../public/copy-session.css'),'utf8');assert.match(css,/min-height:44px/);assert.match(css,/:focus-visible/);});
