'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const Guide=require('../public/guidance22.js'),source=fs.readFileSync(path.join(__dirname,'../public/guidance22.js'),'utf8');
const os=require('node:os');
const alert=(type,id,values={})=>({id,type,sessionKey:'session-'+id,agent:'codex',projectKey:'project-a',values,priority:10});
const context=alert('context','full',{percent:76,handoffFile:'handoff-2030-01-01-001.md',projectName:'Garden'});
const quiet=alert('quiet-project','quiet',{projectName:'Garden',days:8});
function fixture(){return {tasks:[],queue:[],board:{connected:false},guidance:{alerts:[context,quiet,alert('many-projects','many',{count:4})],settings:{quietDays:7},projects:[{key:'a',name:'Garden',state:'active'},{key:'b',name:'Clock',state:'active'},{key:'c',name:'Book',state:'active'},{key:'d',name:'Map',state:'active'},{key:'later-b',name:'Second',state:'queued',queueOrder:2},{key:'later-a',name:'First',state:'queued',queueOrder:1}]}};}
class Node{
  constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.attributes={};this.className='';this.open=false;this.closed=0;}
  append(...nodes){this.children.push(...nodes);for(const n of nodes)if(n&&typeof n==='object')n.parent=this;}
  prepend(...nodes){this.children.unshift(...nodes);for(const n of nodes)if(n&&typeof n==='object')n.parent=this;}
  replaceChildren(...nodes){this.children=[];this.append(...nodes);}
  setAttribute(k,v){this.attributes[k]=v;}
  removeAttribute(k){delete this.attributes[k];}
  getAttribute(k){return this.attributes[k]??null;}
  querySelectorAll(selector){const out=[];for(const n of this.children){if(!n||typeof n!=='object')continue;if(selector.startsWith('.')?n.className.split(' ').includes(selector.slice(1)):n.tagName===selector)out.push(n);out.push(...n.querySelectorAll(selector));}return out;}
  querySelector(s){return this.querySelectorAll(s)[0]||null;}
  remove(){if(this.parent)this.parent.children=this.parent.children.filter(n=>n!==this);}
  close(){this.closed++;this.open=false;}
  focus(){this.focused=true;}
  requestSubmit(){return this.onsubmit?.({preventDefault(){}});}
  set innerHTML(value){throw Error('Unsafe HTML: '+value);}
}
function browser(options={}){const saved=new Map(),nodes={drawer:new Node('dialog'),'view-queue':new Node('section'),refresh:new Node('button')},requests=[],copied=[];
  const document={createElement:tag=>new Node(tag),getElementById:id=>nodes[id]||nodes['view-queue'].querySelectorAll('section').find(n=>n.id===id)||null,querySelector:s=>s.startsWith('#drawer ')?nodes.drawer.querySelector(s.slice(8)):null};
  const window={document,navigator:{clipboard:{writeText:async text=>{if(options.clipboardDenied)throw Error('denied');copied.push(text);}}},localStorage:{getItem:key=>saved.get(key)||null,setItem:(key,v)=>saved.set(key,v)},fetch:async(url,init)=>{requests.push({url,method:init.method,body:JSON.parse(init.body)});return {ok:options.saveFailed!==true,json:async()=>({ok:true})};},panelDrawer(title,children){window.title=title;nodes.drawer.open=true;nodes.drawer.replaceChildren(...children);},PanelLook:{draw(){}},PanelLookViews:{draw(){}},PanelBell:{update(){}}};
  nodes.refresh.click=()=>{};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../public/copy-session.js'),'utf8'),{window});vm.runInNewContext(source,{window});return {window,document,nodes,requests,copied,saved,G:window.PanelGuidance};}
test('unknown context does not alert; one alert per session and type dismissal are shared by cards and bell',()=>{const s=fixture();s.guidance.alerts.push({...context,id:'duplicate',type:'effort-read'});s.guidance.alerts.push(alert('context','unknown',{percent:null}));assert.equal(Guide.alerts(s).length,3);assert.equal(Guide.alerts(s,['context']).some(a=>a.type==='context'),false);assert.equal(Guide.bellItems(s,'en').filter(a=>a.guidanceId==='full').length,1);});
test('final handoff instructions, metadata note and table exist in all three languages without executing them',()=>{for(const lang of ['en','pt','es']){const c=Guide.describe(context,lang);assert.equal(c.copies.length,2);assert.ok(c.copies.every(text=>text.includes(context.values.handoffFile)));assert.match(c.copies[0],/Then stop\.|Depois pare\.|Después detente\./);assert.equal(Guide.T[lang].tableRows.length,6);assert.equal(Guide.T[lang].tableRows[2].length,3);assert.ok(Guide.T[lang].metadata);assert.ok(!/[\u2013\u2014]/.test(JSON.stringify(c)));}assert.equal(Guide.describe(alert('effort-read','e'),'en').copies.length,1);});
test('clipboard copies two exact instructions only after click, with no request; blocked clipboard keeps visible manual text',async()=>{const b=browser();b.G.update(fixture(),'pt');assert.equal(b.requests.length,0);b.G.open('full');const copies=b.nodes.drawer.querySelectorAll('.guidance-copy');assert.equal(b.copied.length,0);await copies[0].onclick();await copies[1].onclick();assert.deepEqual(b.copied,Guide.describe(context,'pt').copies);assert.equal(b.requests.length,0);const blocked=browser({clipboardDenied:true});blocked.G.update(fixture(),'en');blocked.G.open('full');await blocked.nodes.drawer.querySelector('.guidance-copy').onclick();assert.equal(blocked.nodes.drawer.querySelector('.copy-session-fallback').hidden,false);assert.equal(blocked.nodes.drawer.querySelector('.copy-session-status').textContent,blocked.window.PanelCopySession.T.en.failed);assert.ok(blocked.nodes.drawer.querySelectorAll('pre').some(n=>n.textContent===Guide.describe(context,'en').copies[0]));});
test('hide persists only alert type in this browser; resolved snapshot removes stale alert',()=>{const b=browser();b.G.update(fixture(),'en');b.G.open('full');b.nodes.drawer.querySelector('.guidance-hide').onclick();assert.deepEqual(JSON.parse(b.saved.get(Guide.STORE)),['context']);assert.equal(b.G.bellItems().some(n=>n.guidanceId==='full'),false);assert.equal(b.G.sessionCard('session-full'),null);b.G.update({...fixture(),guidance:{...fixture().guidance,alerts:[]}},'en');assert.equal(b.G.bellItems().length,0);});
test('queue order is internal and retained when task folder is disconnected',()=>{const b=browser(),s=fixture();b.G.update(s,'es');assert.deepEqual(Guide.queueProjects(s).map(p=>p.key),['later-a','later-b']);const queue=b.document.getElementById('guidance-queue');assert.ok(queue);assert.equal(queue.querySelector('h2').textContent,'Cola');assert.deepEqual(queue.querySelectorAll('li').map(n=>n.dataset.projectKey),['later-a','later-b']);assert.equal(b.requests.length,0);queue.querySelector('.guidance-link').onclick();assert.equal(b.window.title,'Cronograma');assert.equal(b.nodes.drawer.querySelectorAll('strong').length,2);});
test('pause and close change panel state via explicit local POST; no project content instruction is sent',async()=>{const b=browser();b.G.update(fixture(),'en');b.G.open('quiet');const actions=b.nodes.drawer.querySelectorAll('.guidance-button');actions.find(n=>n.textContent==='Pause').onclick();const form=b.nodes.drawer.querySelector('form');form.querySelector('input').value='2030-04-03';await form.requestSubmit();assert.deepEqual(b.requests[0],{url:'/api/guidance-settings',method:'POST',body:{projectKey:'project-a',state:'paused',resumeAt:'2030-04-03'}});b.G.open('quiet');await b.nodes.drawer.querySelectorAll('.guidance-button').find(n=>n.textContent==='Close').onclick();assert.deepEqual(b.requests[1].body,{projectKey:'project-a',state:'closed'});assert.equal(b.nodes.drawer.open,false);});
test('choose exactly three projects queues the rest in the displayed order, and quiet-days setting validates input',async()=>{const b=browser();b.G.update(fixture(),'en');b.G.open('many');const pick=b.nodes.drawer.querySelector('.guidance-button');pick.onclick();let form=b.nodes.drawer.querySelector('form');await form.requestSubmit();assert.deepEqual(b.requests[0].body,{activeProjects:['a','b','c'],queueOrder:['d','later-a','later-b']});form.querySelectorAll('input')[3].checked=true;await form.requestSubmit();assert.equal(b.requests.length,1);assert.equal(form.querySelector('.guidance-status').textContent,Guide.T.en.pickCount);b.G.settings();form=b.nodes.drawer.querySelector('form');form.querySelector('input').value='10';await form.requestSubmit();assert.deepEqual(b.requests[1].body,{quietDays:10});form.querySelector('input').value='0';await form.requestSubmit();assert.equal(b.requests.length,2);});
test('teach table lives inside closed advanced options and is not duplicated when drawer opens again',()=>{const b=browser();b.G.update(fixture(),'es');const advanced=new Node('details');advanced.className='teach-advanced';b.window.panelDrawer('Enseña a tu IA',[advanced]);assert.equal(advanced.open,false);assert.equal(advanced.querySelectorAll('.guidance-table').length,1);assert.equal(advanced.querySelectorAll('td').length,18);b.G.teachTable('es');assert.equal(advanced.querySelectorAll('.guidance-table').length,1);});
test('session card and instructions are text nodes even with markup-like project metadata',()=>{const b=browser(),s=fixture();s.guidance.alerts=[alert('mixed-projects','mixed',{projectA:'<img src=x>',projectB:'<script>bad</script>'})];b.G.update(s,'en');const c=b.G.sessionCard('session-mixed');assert.ok(c.querySelector('p').textContent.includes('<script>bad</script>'));assert.equal(b.G.sessionCard('missing'),null);assert.doesNotMatch(source,/eval\(|new Function|innerHTML|XMLHttpRequest|WebSocket|sendBeacon/);});
test('queue arrows change stored order, keep keyboard focus and exclude paused/closed projects',async()=>{const b=browser(),s=fixture();s.guidance.projects.push({key:'paused',name:'Paused',state:'paused'},{key:'closed',name:'Closed',state:'closed'});b.G.update(s,'en');b.G.open('many');b.nodes.drawer.querySelector('.guidance-button').onclick();const form=b.nodes.drawer.querySelector('form'),move=()=>form.querySelectorAll('.guidance-move').find(n=>n.dataset.projectKey==='later-b'&&n.dataset.move==='-1');move().onclick();move().onclick();assert.equal(form.querySelectorAll('.guidance-move').find(n=>n.dataset.projectKey==='later-b'&&n.dataset.move==='1').focused,true);await form.requestSubmit();assert.deepEqual(b.requests[0].body.queueOrder,['later-b','d','later-a']);assert.equal(form.querySelectorAll('input').length,6);});
test('failed setting response stays visible and does not close the project',async()=>{const b=browser({saveFailed:true});b.G.update(fixture(),'pt');b.G.open('quiet');await b.nodes.drawer.querySelectorAll('.guidance-button').find(n=>n.textContent==='Fechar').onclick();assert.equal(b.nodes.drawer.open,true);assert.equal(b.nodes.drawer.querySelector('.guidance-status').textContent,Guide.T.pt.saveFailed);});
test('quiet project attaches by project id only without a direct session warning; many-projects remains global',()=>{const b=browser(),s=fixture();s.guidance.alerts=[{...quiet,sessionKey:null,projectKey:'a'},alert('many-projects','many',{count:4})];b.G.update(s,'pt');const a={id:'s1',sessionKey:'direct',projectId:'a'};assert.equal(b.G.sessionCard(a).dataset.guidanceType,'quiet-project');s.guidance.alerts.unshift({...context,sessionKey:'direct'});b.G.update(s,'pt');assert.equal(b.G.sessionCard(a).dataset.guidanceType,'context');assert.equal(b.G.sessionCard({id:'s2',projectId:'b'}),null);assert.equal(b.G.sessionCard(null),null);});
test('legacy task connection opens First steps without requesting a path or sending a folder',()=>{const panel=fs.readFileSync(path.join(__dirname,'../public/panel.js'),'utf8'),functionSource=panel.match(/function connectObservedTasks\(\) \{[\s\S]*?\n\}/)?.[0];assert.ok(functionSource);assert.match(panel,/window\.PanelR4\.connect = connectObservedTasks/);for(const hasEntry of [true,false]){const calls=[],nodes={drawer:{close(){calls.push('close');}},'first-steps-menu':hasEntry?{click(){calls.push('first-steps');}}:null};const window={PanelV2:{select(tab,focus){calls.push([tab,focus]);}},fetch(){assert.fail('Connection must not send an arbitrary folder');},prompt(){assert.fail('Connection must not request a path');}};vm.runInNewContext(functionSource+';connectObservedTasks();',{$:id=>nodes[id],window});assert.deepEqual(calls,hasEntry?['close','first-steps']:['close',['home',true]]);}});
test('pause, close, ordered priorities and quiet days reach the real local API with fictional metadata only',async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'guidance-ui-')),sample=require('../example.json'),keys=['a0a0a0a0','b0b0b0b0','c0c0c0c0','d0d0d0d0'],usage={...sample.usage,ready:true,errors:0,sessions:keys.map((key,i)=>({...sample.usage.sessions[0],id:'fixture-'+i,sessionKey:'fixture-'+i,projectId:key,projectName:'Project '+i,state:'working',activityAt:new Date().toISOString(),startedAt:new Date().toISOString()}))},metrics={index:{metadata:new Map()},published:{},last:Date.now(),running:false,pending:false,snapshot:()=>usage,refresh:async()=>{}},server=require('../src/panel.cjs').createServer({profile,metrics,board:{snapshot:()=>({tasks:[],queue:[],board:{connected:false}})},demoOnly:false});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port,read=async()=>{const r=await fetch(url+'/api/status');assert.equal(r.status,200);return r.json();},post=body=>fetch(url+'/api/guidance-settings',{method:'POST',headers:{Origin:url,'Content-Type':'application/json'},body:JSON.stringify(body)});try{assert.equal((await read()).guidance.projects.length,4);assert.equal((await post({quietDays:10})).status,200);assert.equal((await read()).guidance.settings.quietDays,10);assert.equal((await post({projectKey:keys[0],state:'paused',resumeAt:'2030-04-03'})).status,200);assert.equal((await read()).guidance.projects.find(p=>p.key===keys[0]).state,'paused');assert.equal((await post({projectKey:keys[0],state:'closed'})).status,200);assert.equal((await read()).guidance.projects.find(p=>p.key===keys[0]).state,'closed');assert.equal((await post({projectKey:keys[0],state:'active'})).status,200);assert.equal((await post({activeProjects:keys.slice(0,3),queueOrder:[keys[3]]})).status,200);assert.deepEqual(Guide.queueProjects(await read()).map(p=>p.key),[keys[3]]);assert.equal((await post({projectKey:keys[0],state:'paused',resumeAt:'2030-04-03T00:00:00Z'})).status,400);}finally{await new Promise(r=>server.close(r));const resolved=path.resolve(profile);if(resolved.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(resolved).startsWith('guidance-ui-'))fs.rmSync(resolved,{recursive:true,force:true});}});

test('each project shows its own global-rules reading, with unknown kept distinct from missing',()=>{
  const expected={en:['Global rules found','Global rules not found','Global rules not read'],pt:['Regras globais encontradas','Regras globais não encontradas','Regras globais não lidas'],es:['Reglas globales encontradas','Reglas globales no encontradas','Reglas globales no leídas']};
  for(const lang of ['en','pt','es']){
    const b=browser(),s={example:false,guidance:{projects:[{key:'a',rulesEnabled:true},{key:'b',rulesEnabled:false},{key:'c',rulesEnabled:null}]}};
    for(const [index,key]of ['a','b','c'].entries()){
      const row=b.G.projectRules(s,{id:key,name:'Project '+key},lang);
      assert.equal(row.querySelector('p').textContent,expected[lang][index]);
      assert.equal(row.dataset.rulesState,['found','missing','unknown'][index]);
      assert.equal(row.querySelectorAll('button').length,1);
    }
  }
});
test('unobserved and invalid rule metadata stays unread, while examples are explicitly fictional',()=>{
  const b=browser();
  for(const data of [null,{guidance:{projects:[]}},{guidance:{projects:[{key:'a',rulesEnabled:'true'}]}}])assert.equal(b.G.projectRules(data,{id:'a',name:'Project'},'pt').dataset.rulesState,'unknown');
  const example=b.G.projectRules({example:true,guidance:{projects:[{key:'a',rulesEnabled:true}]}},{id:'a',name:'Project'},'pt');assert.equal(example.dataset.rulesState,'example');assert.equal(example.querySelector('p').textContent,'Regras: exemplo');
});
test('the project rules action only opens teaching after click with the chosen language and current reading',()=>{
  for(const lang of ['en','pt','es']){
    const b=browser(),s={guidance:{projects:[{key:'a',rulesEnabled:false}]}},opened=[];
    b.window.PanelTeach={open:(...args)=>opened.push(args)};
    const row=b.G.projectRules(s,{id:'a',name:'Garden'},lang),action=row.querySelector('button');
    assert.equal(opened.length,0);assert.equal(action.dataset.rulesProject,'a');assert.equal(action.attributes['aria-label'],action.textContent+': Garden');action.onclick();assert.deepEqual(opened,[[lang,s]]);assert.equal(b.requests.length,0);assert.equal(b.copied.length,0);
  }
});
