'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {metadata,publicMetadata}=require('../src/lib/agent-metadata.cjs');
test('context uses the last input and an explicit runtime window, never cumulative tokens',()=>{let m=metadata(JSON.stringify({type:'event_msg',payload:{info:{total_token_usage:{input_tokens:999999,total_tokens:1000000},last_token_usage:{input_tokens:120000},model_context_window:200000}}}));assert.equal(publicMetadata(m).contextPercent,60);m=metadata(JSON.stringify({type:'event_msg',payload:{info:{total_token_usage:{input_tokens:999999,total_tokens:1000000}}}}));assert.equal(publicMetadata(m).contextPercent,null);});
test('model name alone does not invent an ambiguous context window',()=>{const m=metadata(JSON.stringify({type:'turn_context',payload:{model:'claude-opus-4-6'}}));assert.equal(publicMetadata(m).contextWindow,null);});
test('project history resolves sibling subfolders to one repository root',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'guide-roots-'));try{for(const p of ['one/.git','one/a','one/b','two/.git'])fs.mkdirSync(path.join(root,p),{recursive:true});fs.writeFileSync(path.join(root,'one/a/package.json'),'{}');let m=metadata(JSON.stringify({type:'turn_context',payload:{cwd:path.join(root,'one/a')}}));m=metadata(JSON.stringify({type:'turn_context',payload:{cwd:path.join(root,'one/b')}}),m);assert.equal(publicMetadata(m).projectHistory.length,1);m=metadata(JSON.stringify({type:'turn_context',payload:{cwd:path.join(root,'two')}}),m);assert.equal(publicMetadata(m).projectHistory.length,2);assert.ok(!JSON.stringify(publicMetadata(m)).includes(root));}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('readonly advice requires a complete non-sampled projection',()=>{assert.equal(publicMetadata({metadataComplete:true,sampled:true}).metadataComplete,false);assert.equal(publicMetadata({metadataComplete:true,toolTruncated:true}).metadataComplete,false);assert.equal(publicMetadata({metadataComplete:true}).metadataComplete,true);});

test('changing model clears the previous context denominator until the runtime reports it again',()=>{const prev={model:'gpt-example',contextWindow:200000,lastInputTokens:120000};const next=metadata(JSON.stringify({type:'turn_context',payload:{model:'gpt-other'}}),prev);assert.equal(publicMetadata(next).contextPercent,null);});

test('a message beyond the bounded tool projection cannot count as a complete readonly scan',()=>{const content=Array.from({length:17},(_,i)=>({type:'tool_use',name:i===16?'Write':'Read',id:'fixture'+i}));const next=metadata(JSON.stringify({type:'assistant',message:{content}}),{metadataComplete:true});assert.equal(publicMetadata(next).metadataComplete,false);});
