'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createServer}=require('../src/panel.cjs');
test('local guidance API rejects foreign writes and unknown paths, connects only observed existing tasks and detects five steps',async()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'panel22-api-')),project=path.join(temp,'project');fs.mkdirSync(project);fs.mkdirSync(path.join(temp,'.claude'));fs.writeFileSync(path.join(temp,'.claude/CLAUDE.md'),'private example\n## Lazy Du Agent Panel\n');const ruleAt=fs.statSync(path.join(temp,'.claude/CLAUDE.md')).mtimeMs,key='abcdef12',usage={ready:true,sessions:[{id:'fixture',sessionKey:'fixture',agent:'codex',projectId:key,projectName:'project',state:'recent',startedAt:new Date(ruleAt+10000).toISOString(),activityAt:new Date().toISOString()}]},metrics={published:{},index:{metadata:new Map([['synthetic',{privateProjectRoots:[{key,folder:project,name:'project'}]}]])},last:Date.now(),running:false,pending:false,snapshot:()=>usage};const server=createServer({profile:temp,base:temp,metrics,offline:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 const post=(body,route='/api/guidance-settings',origin=url)=>fetch(url+route,{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(body)});
 try{let reading=await(await fetch(url+'/api/status')).json();assert.deepEqual(reading.guidance.onboarding.steps,{running:true,rules:true,newSession:true,task:false,decision:false});assert.ok(!JSON.stringify(reading).includes(temp));assert.ok(!JSON.stringify(reading).includes('private example'));assert.equal((await post({quietDays:10},undefined,'https://outside.example')).status,403);assert.equal((await post({folder:temp})).status,400);assert.equal((await post({projectKey:'abcdef13'},'/api/onboarding-connect')).status,400);assert.equal((await post({projectKey:key},'/api/onboarding-connect')).status,400);assert.ok(!fs.existsSync(path.join(project,'tasks')));fs.mkdirSync(path.join(project,'tasks'));fs.writeFileSync(path.join(project,'tasks/first.md'),'---\nphase: doing\n---\n# Example task\n');fs.writeFileSync(path.join(project,'tasks/decisions.md'),'## 1. Example choice DONE\n');assert.equal((await post({projectKey:key},'/api/onboarding-connect')).status,200);reading=await(await fetch(url+'/api/status')).json();assert.equal(reading.guidance.onboarding.steps.task,true);assert.equal(reading.guidance.onboarding.steps.decision,true);assert.equal((await post({quietDays:12})).status,200);assert.equal((await(await fetch(url+'/api/status')).json()).guidance.settings.quietDays,12);assert.equal((await post({projectKey:key,state:'paused',resumeAt:'2026-02-30'})).status,400);assert.equal((await post({projectKey:key,state:'closed'})).status,200);assert.equal((await(await fetch(url+'/api/status')).json()).guidance.projects[0].state,'closed');assert.equal((await fetch(url+'/onboarding22.js')).status,200);assert.equal((await fetch(url+'/guidance22.css')).status,200);
 }finally{await new Promise(r=>server.close(r));fs.rmSync(temp,{recursive:true,force:true});}
});
test('priority preferences require exactly three active choices and the entire ordered queue',()=>{const {createSettings}=require('../src/lib/guidance-settings.cjs'),store=createSettings('',{persist:false}),keys=['abcdef12','abcdef13','abcdef14','abcdef15'];assert.throws(()=>store.update({activeProjects:keys.slice(0,2),queueOrder:keys.slice(2)},keys));assert.throws(()=>store.update({activeProjects:keys.slice(0,3),queueOrder:[]},keys));store.update({activeProjects:keys.slice(0,3),queueOrder:[keys[3]]},keys);assert.equal(store.snapshot().projects[keys[3]].queueOrder,0);});

test('metadata and task connections write only their own profile cache, not the project',t=>{const {Metrics}=require('../src/lib/usage.cjs'),{TaskBoard}=require('../src/lib/task-board.cjs');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'guide-cache-')),profile=path.join(temp,'profile'),project=path.join(temp,'project');fs.mkdirSync(profile);fs.mkdirSync(project);fs.mkdirSync(path.join(project,'tasks'));t.after(()=>fs.rmSync(temp,{recursive:true,force:true}));const metrics=new Metrics(profile);assert.equal(path.dirname(metrics.cache.dir),path.join(profile,'.lazy-du-panel','metadata'));const board=new TaskBoard(project,{profile});board.connect(path.join(project,'tasks'));assert.ok(fs.existsSync(path.join(profile,'.lazy-du-panel','task-board.json')));assert.deepEqual(fs.readdirSync(project),['tasks']);});

test('saved project choices stay within the restart reader limit',()=>{const {createSettings}=require('../src/lib/guidance-settings.cjs'),store=createSettings('',{persist:false}),keys=Array.from({length:129},(_,i)=>i.toString(16).padStart(8,'0'));for(const id of keys.slice(0,128))store.update({projectKey:id,state:'closed'},keys);assert.throws(()=>store.update({projectKey:keys[128],state:'closed'},keys));assert.equal(Object.keys(store.snapshot().projects).length,128);});
