'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../public/welcome.js'),'utf8');
function harness({lang='en',saved=null,guide=true,guided=false,view='home'}={}){
 const ids=new Map(),storage=new Map(saved?[['agent-panel-profile',JSON.stringify(saved)]]:[]),document={body:{dataset:{view}},documentElement:{lang},activeElement:null};
 class Element{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.attrs={};this.hidden=false;this.ownText='';this.classList={add(){},remove(){},toggle(){}};}set id(id){this._id=id;ids.set(id,this);}get id(){return this._id;}set textContent(v){this.ownText=String(v);this.children=[];}get textContent(){return this.ownText+this.children.map(n=>n.textContent).join(' ');}append(...nodes){this.children.push(...nodes);}prepend(...nodes){this.children.unshift(...nodes);}replaceChildren(...nodes){this.children=nodes;this.ownText='';}contains(node){return this===node||this.children.some(n=>n.contains(node));}setAttribute(k,v){this.attrs[k]=v;}focus(){document.activeElement=this;}scrollIntoView(){}querySelectorAll(tag){return this.children.flatMap(n=>[...(n.tagName===tag?[n]:[]),...n.querySelectorAll(tag)]);}querySelector(selector){if(selector.startsWith('.'))return this.children.flatMap(n=>[n,...n.children]).find(n=>n.className===selector.slice(1));return this.querySelectorAll(selector)[0];}}
 document.createElement=tag=>new Element(tag);document.getElementById=id=>ids.get(id);
 for(const id of ['welcome','setup-guide','quit-panel','tab-home','tab-team','tab-usage','main','first-steps-menu']){const n=new Element('div');n.id=id;}
 const selections=[],started=[],skipped=[],window={document,location:{search:'?lang='+lang},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},PanelV2:{select:v=>selections.push(v)},PanelClean:{setProfile:p=>window.profile=p}};
 let guideFocused=0;if(guide)window.PanelOnboarding={start:options=>started.push(JSON.parse(JSON.stringify(options))),skip:options=>skipped.push(JSON.parse(JSON.stringify(options))),isGuiding:()=>guided,focus:()=>guideFocused++};
 vm.runInNewContext(source,{window,URLSearchParams});const host=ids.get('welcome');
 const click=text=>{const b=host.querySelectorAll('button').find(n=>n.textContent===text);assert.ok(b,text);b.onclick();};
 return{window,storage,host,click,selections,started,skipped,guideFocused:()=>guideFocused};
}
const locales={en:{size:'Just me',goal:'My next step',skip:'Skip for now'},pt:{size:'Só eu',goal:'Meu próximo passo',skip:'Pular por agora'},es:{size:'Solo yo',goal:'Mi siguiente paso',skip:'Omitir por ahora'}};
const metadata={desktop:false,example:false,usage:{sessions:Array.from({length:15},(_,i)=>({id:'synthetic-'+i,projectId:'00000001',projectName:'Example project',state:'resting'}))}};
test('fresh browser with fifteen previous metadata sessions retains the two-choice welcome',()=>{const h=harness();h.window.PanelWelcome.render(metadata,'en');assert.equal(h.host.hidden,false);assert.equal(h.window.document.body.dataset.welcome,'on');assert.equal(h.storage.has('agent-panel-profile'),false);h.window.PanelWelcome.language('pt');h.window.PanelWelcome.render(metadata,'pt');assert.equal(h.host.hidden,false);assert.equal(h.started.length,0);});
test('two deliberate choices start guided next step in each locale without accepting team rules',()=>{for(const [lang,labels]of Object.entries(locales)){const h=harness({lang});h.click(labels.size);assert.equal(h.host.hidden,false);assert.equal(h.started.length,0);h.click(labels.goal);assert.equal(h.host.hidden,true);assert.deepEqual(h.started,[{goal:'next'}]);assert.equal(h.skipped.length,0);assert.equal(JSON.parse(h.storage.get('agent-panel-profile')).size,'solo');assert.equal(h.storage.has('lazydu-first-steps-22'),false,'Only actual onboarding module may save observations');}});
test('existing profile remains dashboard mode until an explicit revisit',()=>{const profile={version:2,size:'large',goal:'usage',mode:'pro',skipped:false},h=harness({saved:profile});h.window.PanelWelcome.render(metadata,'en');assert.equal(h.host.hidden,true);assert.equal(h.started.length,0);assert.deepEqual(JSON.parse(h.storage.get('agent-panel-profile')),profile);h.window.PanelWelcome.show();assert.equal(h.host.hidden,false);assert.equal(h.started.length,0);});
test('initial skip delegates skip rather than entering guided onboarding',()=>{for(const [lang,labels]of Object.entries(locales)){const h=harness({lang});h.click(labels.skip);assert.equal(h.host.hidden,true);assert.equal(h.started.length,0);assert.deepEqual(h.skipped,[{goal:'next'}]);assert.equal(JSON.parse(h.storage.get('agent-panel-profile')).skipped,true);}});
test('cancelling a revisit preserves existing profile choices',()=>{const profile={version:2,size:'large',goal:'usage',mode:'pro',skipped:false},h=harness({saved:profile});h.window.PanelWelcome.show();h.click('Just me');h.click('Skip for now');assert.deepEqual(JSON.parse(h.storage.get('agent-panel-profile')),profile);assert.equal(h.started.length,0);});
test('legacy welcome works when guided module is absent',()=>{const h=harness({guide:false});h.click('Small team');h.click('My team');assert.equal(h.host.hidden,true);assert.equal(h.selections.at(-1),'team');});
test('welcome redraw retains owned goal focus across reading and locale changes',()=>{const h=harness();h.click('Just me');h.window.document.getElementById('welcome-choice-next').focus();h.window.PanelWelcome.render(metadata,'en');assert.equal(h.window.document.activeElement,h.window.document.getElementById('welcome-choice-next'));h.window.PanelWelcome.language('pt');assert.equal(h.window.document.activeElement,h.window.document.getElementById('welcome-choice-next'));assert.equal(h.window.document.activeElement.textContent,'Meu próximo passo');assert.equal(h.host.hidden,false);});
test('welcome redraw never steals deliberately external focus',()=>{const h=harness();const external=h.window.document.getElementById('setup-guide');external.focus();h.window.PanelWelcome.render(metadata,'en');assert.equal(h.window.document.activeElement,external);assert.equal(h.host.hidden,false);});
test('cancelling welcome while an unfinished guide is on Team or Usage returns to the visible tab',()=>{for(const view of ['team','usage']){const profile={version:2,size:'large',goal:view,mode:'pro',skipped:false},h=harness({saved:profile,guided:true,view});h.window.PanelWelcome.show();h.click('Skip for now');assert.deepEqual(JSON.parse(h.storage.get('agent-panel-profile')),profile);assert.equal(h.guideFocused(),0,'Hidden Home guide must not receive focus');assert.equal(h.selections.at(-1),view);assert.equal(h.window.document.activeElement,h.window.document.getElementById('tab-'+view));}});
