'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../public/welcome.js'),'utf8');
function harness({lang='en',saved=null,guide=true,guided=false,view='home',search='',initial={},referrer='',historyLength=1}={}){
 const ids=new Map(),storage=new Map(saved?[['agent-panel-profile',JSON.stringify(saved)]]:[]),document={body:{dataset:{view}},documentElement:{lang},activeElement:null};
 class Element{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.attrs={};this.hidden=false;this.ownText='';this.classList={add(){},remove(){},toggle(){}};}set id(id){this._id=id;ids.set(id,this);}get id(){return this._id;}set textContent(v){this.ownText=String(v);this.children=[];}get textContent(){return this.ownText+this.children.map(n=>n.textContent).join(' ');}append(...nodes){this.children.push(...nodes);}prepend(...nodes){this.children.unshift(...nodes);}replaceChildren(...nodes){this.children=nodes;this.ownText='';}contains(node){return this===node||this.children.some(n=>n.contains(node));}setAttribute(k,v){this.attrs[k]=v;}focus(){document.activeElement=this;}scrollIntoView(){}querySelectorAll(tag){return this.children.flatMap(n=>[...(n.tagName===tag?[n]:[]),...n.querySelectorAll(tag)]);}querySelector(selector){if(selector.startsWith('.'))return this.children.flatMap(n=>[n,...n.children]).find(n=>n.className===selector.slice(1));return this.querySelectorAll(selector)[0];}}
 document.createElement=tag=>new Element(tag);document.getElementById=id=>ids.get(id);
 for(const id of ['welcome','setup-guide','quit-panel','tab-home','tab-team','tab-usage','main','first-steps-menu']){const n=new Element('div');n.id=id;}
 for(const[k,v]of Object.entries(initial))storage.set(k,v);const writes=[],network=[];document.referrer=referrer;const closed=[],navigations=[];const selections=[],started=[],skipped=[],window={document,location:{search:search||'?lang='+lang,origin:'http://127.0.0.1:3215',href:'http://127.0.0.1:3215/'+(search||'?lang='+lang),assign:url=>navigations.push(url)},history:{length:historyLength},close:()=>closed.push(true),setTimeout:fn=>fn(),localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>{writes.push({key:k,value:v});storage.set(k,v);}},fetch:(...args)=>{network.push(args);throw Error('Unexpected network');},PanelV2:{select:v=>selections.push(v)},PanelClean:{setProfile:p=>window.profile=p}};
 let guideFocused=0;if(guide)window.PanelOnboarding={start:options=>started.push(JSON.parse(JSON.stringify(options))),skip:options=>skipped.push(JSON.parse(JSON.stringify(options))),isGuiding:()=>guided,focus:()=>guideFocused++};
 vm.runInNewContext(source,{window,URLSearchParams,URL,setTimeout:fn=>fn(),clearTimeout:()=>{}});const host=ids.get('welcome');
 const click=text=>{const b=host.querySelectorAll('button').find(n=>n.textContent===text);assert.ok(b,text);b.onclick();};
 return{window,storage,host,click,selections,started,skipped,guideFocused:()=>guideFocused,writes,network,closed,navigations};
}
const labels={en:'View example',pt:'Ver exemplo',es:'Ver el ejemplo'};
const metadata={desktop:false,example:false,usage:{sessions:Array.from({length:15},(_,i)=>({id:'fictional-'+i,projectName:'Fictional project',state:'resting'}))}};
function anchor(h){const a=h.window.document.getElementById('welcome-example');assert.ok(a,'Example entry is available before setup');assert.equal(a.tagName,'a');return a;}
function verifyLink(h,lang){const a=anchor(h),url=new URL(a.href,'http://127.0.0.1:3215');assert.equal(url.origin,'http://127.0.0.1:3215');assert.equal(url.pathname,'/');assert.equal(url.searchParams.get('example'),'1');assert.equal(url.searchParams.get('size'),'solo');assert.equal(url.searchParams.get('lang'),lang);assert.equal(url.searchParams.get('entry'),'welcome');assert.equal(a.target,'_blank');assert.equal(a.referrerPolicy,'same-origin');assert.ok(a.rel.split(/\s+/).includes('noopener'));assert.equal(a.onclick,undefined,'A native navigation anchor does not save setup');assert.equal(a.textContent,labels[lang]);return a;}
test('three locales expose example before choosing size, without saving preferences or observations',()=>{for(const lang of Object.keys(labels)){const h=harness({lang});h.window.PanelWelcome.render(metadata,lang);verifyLink(h,lang);assert.equal(h.host.hidden,false);assert.equal(h.host.querySelector('.clean-step').textContent,'1 / 2');assert.equal(h.writes.length,0);assert.equal(h.network.length,0);assert.equal(h.started.length,0);assert.equal(h.skipped.length,0);}});
test('example remains a separate-tab action in the goal stage without committing size',()=>{for(const lang of Object.keys(labels)){const h=harness({lang});h.window.document.getElementById('welcome-choice-small').onclick();verifyLink(h,lang);assert.equal(h.host.querySelector('.clean-step').textContent,'2 / 2');assert.equal(h.writes.length,0);assert.equal(h.started.length,0);}});
test('locale refresh updates the example destination and retains the setup stage',()=>{const h=harness();h.window.document.getElementById('welcome-choice-small').onclick();for(const lang of ['pt','es','en']){h.window.PanelWelcome.language(lang);verifyLink(h,lang);assert.equal(h.host.querySelector('.clean-step').textContent,'2 / 2');}assert.equal(h.writes.length,0);});
test('existing profile and unfinished guide are untouched during a welcome revisit',()=>{const profile={version:2,size:'large',goal:'usage',mode:'pro',skipped:false},guide=JSON.stringify({guided:true,goal:'usage',observed:{fictional:{task:true}},skipped:false}),h=harness({saved:profile,guided:true,initial:{'lazydu-first-steps-22':guide,'agent-panel-language':'es'}});const before=[...h.storage];h.window.PanelWelcome.show();verifyLink(h,'en');h.window.document.getElementById('welcome-choice-small').onclick();verifyLink(h,'en');assert.deepEqual([...h.storage],before);assert.equal(h.writes.length,0);assert.equal(h.network.length,0);assert.equal(h.started.length,0);});
test('viewing example does not make an existing real setup active or mark any step done',()=>{const profile={version:2,size:'large',goal:'team',mode:'pro'},h=harness({saved:profile,search:'?example=1&size=solo&lang=pt&entry=welcome'});h.window.PanelWelcome.render({...metadata,example:true},'pt');assert.equal(h.host.hidden,true);assert.deepEqual(JSON.parse(h.storage.get('agent-panel-profile')),profile);assert.equal(h.writes.length,0);assert.equal(h.started.length,0);assert.equal(h.skipped.length,0);});
test('the explicit setup fallback can show welcome while preserving an existing profile',()=>{const profile={version:2,size:'large',goal:'team',mode:'pro'},h=harness({saved:profile,search:'?lang=pt&setup=1'});assert.equal(h.host.hidden,false);verifyLink(h,'pt');assert.deepEqual(JSON.parse(h.storage.get('agent-panel-profile')),profile);assert.equal(h.writes.length,0);});
test('package and installed version fallbacks agree with the new patch',()=>{const root=path.join(__dirname,'..'),version=JSON.parse(fs.readFileSync(path.join(root,'package.json'))).version;assert.equal(version,'2.2.5');for(const file of ['bell.js','quick-start.js','sync.js'])assert.ok(fs.readFileSync(path.join(root,'public',file),'utf8').includes("'"+version+"'"),file+' installed version fallback');});
test('direct entry and unrelated referrers never close an existing browser tab',()=>{for(const config of [{referrer:''},{referrer:'https://example.invalid/other'},{referrer:'http://127.0.0.1:3215/?example=1'},{referrer:'http://127.0.0.1:3215/?lang=pt',historyLength:2}]){const h=harness({search:'?example=1&size=solo&lang=pt&entry=welcome',...config});const link=h.window.document.getElementById('welcome-example-return');assert.ok(link);const target=new URL(link.href,'http://127.0.0.1:3215');assert.equal(target.searchParams.get('example'),null);assert.equal(target.searchParams.get('setup'),'1');assert.equal(target.searchParams.get('lang'),'pt');let prevented=false;link.onclick?.({preventDefault(){prevented=true;}});assert.equal(prevented,false);assert.equal(h.closed.length,0);assert.equal(h.writes.length,0);assert.equal(h.network.length,0);}});
test('a single-history example opened from this origin may close only its own context',()=>{const h=harness({search:'?example=1&size=solo&lang=es&entry=welcome',referrer:'http://127.0.0.1:3215/?lang=es',historyLength:1});const link=h.window.document.getElementById('welcome-example-return');assert.ok(link);let prevented=false;link.onclick({preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(h.closed.length,1);assert.equal(h.writes.length,0);assert.equal(h.network.length,0);const fallback=h.window.document.getElementById('welcome-example-fallback');assert.ok(fallback);assert.equal(fallback.hidden,false,'Blocked native close provides an explicit setup route');});
test('a normal example without the welcome entry flag has no special close action',()=>{const h=harness({search:'?example=1&size=solo&lang=en',referrer:'http://127.0.0.1:3215/?lang=en'});assert.equal(h.window.document.getElementById('welcome-example-return'),undefined);assert.equal(h.closed.length,0);assert.equal(h.writes.length,0);});
test('README introductions contain one real opening action, shipped fictional PNGs and qualified privacy',()=>{for(const[file,heading,cta,privacy]of [['README.md','Open in under a minute','Open the panel',/Connected task folders and the global rules marker are also read;.*optional network features/],['README.pt-BR.md','Abrir em menos de um minuto','Abrir o painel',/pastas de tarefas conectadas e o marcador das regras globais;.*opcionais de rede/]]){const root=path.join(__dirname,'..'),text=fs.readFileSync(path.join(root,file),'utf8'),top=text.slice(0,text.indexOf('\n## '));const primary=[...top.matchAll(/\*\*\[([^\]]+)\]\((#[^)]+)\)\*\*/g)];assert.equal(primary.length,1,'One primary opening action');assert.equal(primary[0][1],cta);assert.equal(primary[0][2],'#'+heading.toLowerCase().replace(/ /g,'-'));assert.ok(text.includes('## '+heading));assert.match(top,privacy);assert.match(top,file==='README.md'?/without decoding conversations or tool arguments/:/sem decodificar conversas ou argumentos de ferramentas/);assert.match(top,file==='README.md'?/Fictional example/:/Exemplo fictício/);const images=[...top.matchAll(/!\[[^\]]+\]\(([^)]+\.png)\)/g)];assert.ok(images.length>0);for(const image of images){assert.ok(!path.isAbsolute(image[1])&&!image[1].split('/').includes('..'));const body=fs.readFileSync(path.join(root,image[1]));assert.equal(body.subarray(0,8).toString('hex'),'89504e470d0a1a0a');}}});

test('Storage probe ignores non-origin initial documents and preserves HTTP storage errors',()=>{
 const runner=fs.readFileSync(path.join(__dirname,'../tools/validate-entry-example23.cjs'),'utf8'),text=runner.slice(runner.indexOf('function installStorageProbe('),runner.indexOf('async function setup('));
 let reads=0;const denied={};Object.defineProperty(denied,'localStorage',{get(){reads++;throw Error('Storage denied at HTTP origin');}});
 const origin='http://127.0.0.1:3215';
 for(const location of [{protocol:'about:',origin:'null'},{protocol:'http:',origin:'http://outside.invalid'}])vm.runInNewContext(text+'installStorageProbe({origin});',{window:denied,location,origin});
 assert.equal(reads,0,'The fixture does not access opaque or unrelated document storage');
 assert.throws(()=>vm.runInNewContext(text+'installStorageProbe({origin});',{window:denied,location:{protocol:'http:',origin},origin}),/Storage denied at HTTP origin/);
 assert.equal(reads,1,'Errors in the served document remain real failures');
 class Storage{constructor(){this.length=0;this.saved=[];}setItem(...args){this.saved.push(args);}removeItem(){}clear(){}}
 const storage=new Storage(),window={localStorage:storage};vm.runInNewContext(text+"installStorageProbe({origin});window.localStorage.setItem('example','value');",{window,location:{protocol:'http:',origin},origin,Storage});
 assert.equal(window.__entryWrites.length,1);assert.deepEqual(storage.saved,[['example','value']]);
});

test('Demo preferences use fresh document memory while normal preferences retain their original store',()=>{
 const {createStorage}=require('../public/demo-storage.js'),normal={saved:[]};
 assert.equal(createStorage({location:{search:'?lang=pt'},localStorage:normal}).storage(),normal);
 let touches=0;const context={location:{search:'?example=1&entry=welcome'}};Object.defineProperty(context,'localStorage',{get(){touches++;throw Error('Demo touched real preferences');}});
 const a=createStorage(context).storage(),b=createStorage(context).storage();
 assert.equal(a.length,0);a.setItem('language','es');a.setItem('profile',123);assert.equal(a.getItem('profile'),'123');assert.equal(a.key(0),'language');assert.equal(a.length,2);assert.equal(b.getItem('language'),null);a.removeItem('profile');assert.equal(a.getItem('profile'),null);a.clear();assert.equal(a.length,0);assert.equal(touches,0);
});
test('Real demo portraits and forecast caches stay stable without reading or writing original preferences',()=>{
 const context={URLSearchParams,location:{search:'?example=1'},DuPortraits:require('../public/dus.json')};let reads=0;Object.defineProperty(context,'localStorage',{get(){reads++;throw Error('Real origin store touched');}});context.window=context;
 vm.createContext(context);for(const name of ['demo-storage.js','crew.js','r4-core.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../public',name),'utf8'),context);
 const list=[{id:'game-code',role:'dev'},{id:'game-art',role:'designer'}],first=context.DuCrew.assign(list),second=context.DuCrew.assign([...list].reverse());
 assert.equal(first[0].du.id,second[1].du.id);assert.equal(first[1].du.id,second[0].du.id);const saved=context.PanelStorage.storage().getItem('agent-panel-du-portraits');assert.ok(JSON.parse(saved)['game-code']);
 const item={id:'game-code',taskDurationsMinutes:[4,8,6]},now=Date.parse('2030-01-01T12:00:00Z'),one=context.PanelR4Core.forecast(item,now);assert.equal(context.PanelR4Core.forecast(item,now+60000).at,one.at);assert.ok(context.PanelStorage.storage().getItem('agent-panel-eta-game-code'));assert.equal(reads,0);
});
test('Legacy isolated module harnesses fail closed in demo when the storage helper is absent',()=>{
 const context={URLSearchParams,location:{search:'?example=1'},DuPortraits:require('../public/dus.json')};let reads=0;Object.defineProperty(context,'localStorage',{get(){reads++;throw Error('Demo fallback touched original store');}});context.window=context;vm.createContext(context);
 for(const name of ['crew.js','r4-core.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../public',name),'utf8'),context);
 assert.equal(context.DuCrew.assign([{id:'game-code'}]).length,1);assert.ok(context.PanelR4Core.forecast({id:'game-code'},Date.parse('2030-01-01T12:00:00Z')).at);assert.equal(reads,0);
});

test('Real example scope settings block forced changes while normal settings retain their API action',async()=>{
 const code=fs.readFileSync(path.join(__dirname,'../public/sync.js'),'utf8'),settings=code.slice(code.indexOf('function settings(){'),code.indexOf('  const radio='));assert.ok(settings.startsWith('function settings(){'));
 class Element{constructor(tag){this.tag=tag;this.children=[];}set disabled(value){this._disabled=Boolean(value);}get disabled(){return this._disabled||false;}append(...nodes){this.children.push(...nodes);}}
 async function check({search='',example=false,removeGuard=false}={}){
  const calls=[],result={refresh:0};const root={location:{search},fetch:async(...args)=>{calls.push(args);return{ok:true};},PanelR4:{connect(){}},panelDrawer(_title,nodes){result.nodes=nodes;}};
  const context={URLSearchParams,root,data:{example,usage:{scopeDays:1}},lang:'en',chat:false,muted:false,tr:x=>x,w:x=>x,el:tag=>new Element(tag),$:()=>({click(){result.refresh++;}}),save(){},update(){}};
  vm.runInNewContext((removeGuard?settings.replace('if(example())return;',''):settings)+';settings();',context);
  const scope=result.nodes[0].children[0].children.find(n=>n.tag==='select');scope.value='7';await scope.onchange();return{scope,calls,result};
 }
 for(const options of [{search:'?example=1'},{search:'?example=%31'},{search:'?%65xample=1'},{example:true}]){const result=await check(options);assert.equal(result.scope.disabled,true);assert.equal(result.calls.length,0);assert.equal(result.result.refresh,0);}
 const normal=await check();assert.equal(normal.scope.disabled,false);assert.equal(normal.calls.length,1);assert.equal(normal.calls[0][0],'/api/scope');assert.equal(normal.calls[0][1].method,'POST');assert.equal(JSON.parse(normal.calls[0][1].body).days,7);assert.equal(normal.result.refresh,1);
 const removed=await check({search:'?example=1',removeGuard:true});assert.equal(removed.calls.length,1,'Removing the real handler guard exposes a write despite the disabled control');
});

test('Encoded and repeated demo query parameters follow the same first-value semantics as the product',()=>{
 const {createStorage}=require('../public/demo-storage.js'),normal={sentinel:'normal'};
 for(const search of ['?example=%31','?%65xample=1','?example=1&example=0']){
  let reads=0;const context={URLSearchParams,location:{search},DuPortraits:require('../public/dus.json')};Object.defineProperty(context,'localStorage',{get(){reads++;throw Error('Encoded demo touched original storage');}});
  const memory=createStorage(context).storage();memory.setItem('check','demo');assert.equal(memory.getItem('check'),'demo');
  context.window=context;vm.createContext(context);for(const name of ['crew.js','r4-core.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../public',name),'utf8'),context);
  assert.equal(context.DuCrew.assign([{id:'encoded-demo'}]).length,1);assert.ok(context.PanelR4Core.forecast({id:'encoded-demo'},Date.parse('2030-01-01T12:00:00Z')).at);assert.equal(reads,0,'Fallback without helper also isolates encoded demos');
 }
 for(const search of ['', '?example=0&example=1'])assert.equal(createStorage({location:{search},localStorage:normal}).storage(),normal);
 assert.equal(createStorage({localStorage:normal}).storage(),normal,'Legacy harnesses without location retain their normal storage');
 const saved=new Map(),storage={getItem:k=>saved.get(k)??null,setItem:(k,v)=>saved.set(k,v)},context={URLSearchParams,DuPortraits:require('../public/dus.json'),localStorage:storage};context.window=context;vm.createContext(context);
 for(const name of ['crew.js','r4-core.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../public',name),'utf8'),context);context.DuCrew.assign([{id:'normal-legacy'}]);context.PanelR4Core.forecast({id:'normal-legacy'},Date.parse('2030-01-01T12:00:00Z'));assert.ok(saved.has('agent-panel-du-portraits'));assert.ok(saved.has('agent-panel-eta-normal-legacy'),'Normal cache persistence remains intact');
});

test('Actual HTTP serves the demo helper as JavaScript before every preference writer',async t=>{
 const os=require('node:os'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'entry-helper-http-')),metrics={snapshot:()=>({sessions:[],ready:false}),refresh:async()=>{}},board={snapshot:()=>({tasks:[],queue:[],board:{connected:false}})};
 const instance=require('../src/panel.cjs').createServer({profile:dir,metrics,board,demoOnly:true,offline:true,updateFetch:null,newsFetch:null});
 await new Promise(resolve=>instance.listen(0,'127.0.0.1',resolve));t.after(async()=>{await new Promise(resolve=>instance.close(resolve));fs.rmSync(dir,{recursive:true,force:true});});
 const origin='http://127.0.0.1:'+instance.address().port,asset=await fetch(origin+'/demo-storage.js');assert.equal(asset.status,200,'Actual helper route must be registered');assert.match(asset.headers.get('content-type'),/^text\/javascript/);const body=await asset.text();assert.equal(body,fs.readFileSync(path.join(__dirname,'../public/demo-storage.js'),'utf8'));
 const context={URLSearchParams,window:{location:{search:'?example=1'}}};Object.defineProperty(context.window,'localStorage',{get(){assert.fail('Served demo helper must not read original preferences');}});vm.runInNewContext(body,context);assert.equal(typeof context.window.PanelStorage?.storage,'function');assert.equal(context.window.PanelStorage.storage().length,0);
 const html=await(await fetch(origin+'/?lang=pt')).text(),scripts=[...html.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]),first=scripts.indexOf('/demo-storage.js');assert.ok(first>=0);for(const name of ['crew.js','r4-core.js','controls211.js','panel.js','v21.js','onboarding22.js','teach.js','guidance22.js','v2.js','tips.js','bell.js','sync.js','welcome.js'])assert.ok(scripts.indexOf('/'+name)>first,'HTTP loader precedes '+name);
});
