const test=require('node:test'),assert=require('node:assert/strict'),{UsageIndex,Metrics}=require('../src/lib/usage.cjs'),{actionOf}=require('../src/lib/session-story.cjs'),R=require('../public/r4-core.js'),H=require('../public/human.js');
const line=(type,timestamp,payload)=>JSON.stringify({type,timestamp,payload});
test('last action gives a concrete bilingual step, not a generic tool category',()=>{assert.deepEqual(actionOf('functions.exec','node --test test/r7.test.cjs'),['Running the tests','Rodando os testes']);assert.deepEqual(actionOf('functions.exec','screenshot Team 375.png'),['Taking Team screenshots','Tirando prints da Equipe']);assert.deepEqual(actionOf('functions.exec','writeFile RELATORIO.md'),['Writing the report','Escrevendo o relatório']);});
test('active means ten-minute activity; finished conversations are not active',()=>{const i=new UsageIndex();for(const [id,at,ended]of [['active','11:51',false],['paused','11:49',false],['done','11:59',true]]){i.consume('codex',id,line('session_meta','2030-01-07T'+at+':00Z',{id,cwd:'/projects/Game',model:'gpt-6.1-sol'}));i.consume('codex',id,line('event_msg','2030-01-07T'+at+':00Z',{type:'user_message',message:'Build the game menu'}));if(ended)i.consume('codex',id,line('event_msg','2030-01-07T'+at+':30Z',{type:'task_complete'}));}const s=i.snapshot(new Date('2030-01-07T12:00:00Z'));assert.deepEqual(s.counts,{active:1,paused:1,finished:1});assert.equal(s.completedToday.length,0);assert.equal(s.finishedSessions.length,1);});
test('Codex day/week totals use ordered cumulative deltas and deduplicate tail rereads',()=>{const i=new UsageIndex(),consume=(at,n)=>i.consume('codex','sample',line('event_msg',at,{type:'token_count',info:{total_token_usage:{total_tokens:n,input_tokens:n,output_tokens:0,cached_input_tokens:0}}}));consume('2030-01-07T00:10:00Z',160);consume('2030-01-06T23:50:00Z',100);consume('2030-01-07T00:10:00Z',160);consume('2030-01-07T01:10:00Z',210);const s=i.snapshot(new Date('2030-01-07T12:00:00Z'));assert.equal(s.periods[0].codex,110);assert.equal(s.periods[1].codex,210);assert.equal(s.periods[0].weightedTokens,110);assert.equal(s.totals.tokens,210);});
test('Claude tokens and water stay separate by period with deduplicated messages',()=>{const i=new UsageIndex();for(const [id,day]of [['a','2030-01-06'],['b','2030-01-07'],['b','2030-01-07']])i.consume('claude','sample',JSON.stringify({type:'assistant',timestamp:day+'T12:00:00Z',message:{id,usage:{input_tokens:100,output_tokens:20,cache_read_input_tokens:100}}}));const s=i.snapshot(new Date('2030-01-07T13:00:00Z'));assert.equal(s.periods[0].claude,220);assert.equal(s.periods[1].claude,440);assert.equal(s.periods[0].weightedTokens,130);});
test('helper retains its proven parent without reading or inheriting prompt text',()=>{const i=new UsageIndex(),id='11111111-1111-1111-1111-111111111111';i.consume('codex','parent',line('session_meta','2030-01-07T12:00:00Z',{id,cwd:'/projects/Game',model:'gpt-6.1-sol'}));i.consume('codex','parent',line('event_msg','2030-01-07T12:01:00Z',{type:'user_message',message:'Build the game menu'}));i.consume('codex','child',line('session_meta','2030-01-07T12:02:00Z',{id:'child',cwd:'/projects/Game',model:'gpt-6.1-sol',source:{subagent:{thread_spawn:{parent_thread_id:id}}}}));i.consume('codex','child',line('event_msg','2030-01-07T12:03:00Z',{type:'token_count',info:{total_token_usage:{total_tokens:5}}}));const s=i.snapshot(new Date('2030-01-07T12:04:00Z')),child=s.sessions.find(s=>s.helper);assert.equal(child.taskTitle,null);assert.ok(child.parentKey);assert.equal(child.projectName,'Game');assert.doesNotMatch(JSON.stringify(s),new RegExp(id));assert.doesNotMatch(R.decorate([child],{},Date.now())[0].title,/HELPER|AJUDANTE/);});
test('names never acquire invented ordinal or alphabetic qualifiers',()=>{const names=R.decorate(Array.from({length:80},(_,i)=>({id:String(i),role:'dev',taskTitle:'GAME',projectName:'Game'})),{},Date.now());for(const s of names){assert.doesNotMatch(s.title,/SECOND|THIRD|FOURTH|FIFTH|SIXTH|SEVENTH|EIGHTH|NINTH|GROUP [A-Z]/);assert.equal(H.forbidden(s.title+' '+s.action),false);}});
test('partial index never becomes public totals and a published snapshot is immutable',()=>{const m=new Metrics('unused'),at='2030-01-07T12:00:00Z';m.index.consume('codex','sample',line('event_msg',at,{type:'token_count',info:{total_token_usage:{total_tokens:100}}}));m.pending=true;assert.equal(m.snapshot().totals.tokens,null);assert.deepEqual(m.snapshot().sessions,[]);m.published=structuredClone(m.index.snapshot(new Date(at)));m.readAt=at;m.index.consume('codex','sample',line('event_msg','2030-01-07T12:01:00Z',{type:'token_count',info:{total_token_usage:{total_tokens:500}}}));assert.equal(m.snapshot().totals.tokens,100);assert.equal(m.snapshot().updated,at);assert.equal(m.snapshot().ready,true);});
test('an identified live process keeps its own old conversation active without promoting the others',()=>{const {key}=require('../src/lib/session-story.cjs');const i=new UsageIndex();for(const id of ['live','old']){i.consume('codex',id,line('session_meta','2030-01-06T12:00:00Z',{id,cwd:'/projects/Game',model:'gpt-6.1-sol'}));}const s=i.snapshot(new Date('2030-01-07T12:00:00Z'),[key('live')]);assert.equal(s.counts.active,1);assert.equal(s.counts.paused,1);});
test('a delimited record larger than one IO window completes even after its time slice expired',async t=>{const fs=require('fs'),os=require('os'),path=require('path'),{readUsage}=require('../src/lib/usage.cjs');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'panel-r7-record-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'sample.jsonl'),text=JSON.stringify({type:'event_msg',timestamp:'2030-01-07T12:00:00Z',payload:{type:'token_count',info:{total_token_usage:{total_tokens:100}},ignored:'x'.repeat(60000)}});fs.writeFileSync(file,text+'\n');const i=new UsageIndex(),state={offset:0,probe:0,lineEnd:Buffer.byteLength(text),lineNext:Buffer.byteLength(text)+1,errors:0};const result=await readUsage(file,'codex',i,{root:dir,state,budget:{bytes:131072,capBytes:131072,read:0,deadline:performance.now()-100}});assert.equal(result.done,true);assert.equal(i.snapshot().totals.tokens,100);});
test('forked conversation copies do not charge the same token events twice by period',()=>{const i=new UsageIndex();i.consume('codex','parent',line('session_meta','2030-01-07T11:00:00Z',{id:'parent',model:'gpt-6.1-sol'}));i.consume('codex','child',line('session_meta','2030-01-07T11:00:00Z',{id:'child',model:'gpt-6.1-sol',source:{subagent:{thread_spawn:{parent_thread_id:'parent'}}}}));for(const file of ['parent','child'])for(const [minute,n]of [['00',10],['01',20]])i.consume('codex',file,line('event_msg','2030-01-07T12:'+minute+':00Z',{type:'token_count',info:{total_token_usage:{total_tokens:n}}}));i.consume('codex','child',line('event_msg','2030-01-07T12:02:00Z',{type:'token_count',info:{total_token_usage:{total_tokens:30}}}));assert.equal(i.snapshot(new Date('2030-01-07T13:00:00Z')).periods[0].codex,30);});

test('helper prompt text does not infer a title or role in the real reader',()=>{const i=new UsageIndex();i.consume('codex','helper',line('session_meta','2030-01-07T12:00:00Z',{id:'child',cwd:'/projects/Game',model:'gpt-6.1-sol',source:{subagent:{thread_spawn:{parent_thread_id:'parent'}}}}));i.consume('codex','helper',line('event_msg','2030-01-07T11:00:00Z',{type:'user_message',message:'Build the game'}));i.consume('codex','helper',line('event_msg','2030-01-07T12:01:00Z',{type:'user_message',message:'Review the prices'}));const s=i.snapshot(new Date('2030-01-07T12:02:00Z')).sessions[0];assert.equal(s.taskTitle,null);assert.equal(s.role,null);assert.doesNotMatch(JSON.stringify(s),/Review the prices|Build the game/);});

test('Claude final text closes a helper even when stop_reason was omitted',()=>{const i=new UsageIndex();i.consume('claude','helper',JSON.stringify({type:'assistant',timestamp:'2030-01-07T12:00:00Z',message:{id:'done',model:'claude-opus-5-5',content:[{type:'text',text:'Checked the report.'}],usage:{input_tokens:100,output_tokens:20}}}));assert.equal(i.snapshot(new Date('2030-01-07T12:01:00Z')).counts.active,0);});
test('a blocked final does not count as a finished task or an active agent',()=>{const i=new UsageIndex();i.consume('codex','blocked',line('session_meta','2030-01-07T12:00:00Z',{id:'blocked',model:'gpt-6.1-sol',cwd:'/projects/Game'}));i.consume('codex','blocked',line('event_msg','2030-01-07T12:01:00Z',{type:'user_message',message:'Build the game'}));i.consume('codex','blocked',line('response_item','2030-01-07T12:02:00Z',{type:'message',role:'assistant',phase:'final_answer',content:[{text:'Not completed. Blocked by missing files.'}]}));const s=i.snapshot(new Date('2030-01-07T12:03:00Z'));assert.equal(s.counts.active,0);assert.equal(s.completedToday.length,0);});
