const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {Metrics}=require('../src/lib/usage.cjs'),{actionOf}=require('../src/lib/session-story.cjs'),R=require('../public/r4-core.js'),H=require('../public/human.js');
const now=new Date('2030-01-07T12:00:00Z');
const line=(type,payload,at='2030-01-07T11:59:00Z')=>JSON.stringify({type,timestamp:at,payload})+'\n';
function fixture(t){const home=fs.mkdtempSync(path.join(os.tmpdir(),'panel-r8-'));t.after(()=>fs.rmSync(home,{recursive:true,force:true}));return home;}
function write(home,id,text,age=0){const f=path.join(home,'.codex/sessions/2030/01/07','rollout-'+id+'.jsonl');fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,text);fs.utimesSync(f,new Date(+now-age),new Date(+now-age));return f;}
const content=id=>line('session_meta',{id,cwd:'/projects/Game',model:'gpt-6.1-sol'})+line('event_msg',{type:'user_message',message:'Build the GAME MENU'})+line('event_msg',{type:'token_count',info:{total_token_usage:{total_tokens:10,input_tokens:8,output_tokens:2,cached_input_tokens:0}}});
function metrics(home,options={}){return new Metrics(home,{clock:()=>now,cacheDir:path.join(home,'cache'),...options});}
async function finish(m){for(let n=0;n<300;n++){await m.refresh();if(!m.pending&&!m.running){clearTimeout(m.nextRound);return m.snapshot();}}throw Error('Reader did not finish');}
test('a second start restores unchanged results without opening conversation files',async t=>{const home=fixture(t);write(home,'one',content('one'));const first=await finish(metrics(home));const original=fs.promises.open;let reads=0;fs.promises.open=async(file,...args)=>{if(String(file).endsWith('.jsonl'))reads++;return original(file,...args);};try{const second=await finish(metrics(home));a.equal(reads,0);a.equal(second.cache.hits,1);a.deepEqual(second.periods,first.periods);a.deepEqual(second.sessions,first.sessions);}finally{fs.promises.open=original;}});
test('size or modification time changes invalidate the per-file cache',async t=>{const home=fixture(t),f=write(home,'one',content('one'));await finish(metrics(home));fs.appendFileSync(f,line('event_msg',{type:'token_count',info:{total_token_usage:{total_tokens:20,input_tokens:18,output_tokens:2,cached_input_tokens:0}}},'2030-01-07T12:00:00Z'));fs.utimesSync(f,now,now);const changed=await finish(metrics(home));a.equal(changed.totals.tokens,20);a.equal(changed.cache.hits,0);const text=fs.readFileSync(f,'utf8').replace('GAME MENU','GAME ART ');fs.writeFileSync(f,text);fs.utimesSync(f,new Date(+now+1000),new Date(+now+1000));const sameSize=await finish(metrics(home));a.equal(sameSize.cache.hits,0);a.equal(sameSize.sessions[0].taskTitle,null);a.equal(sameSize.sessions[0].projectName,'Game');});
test('cache stores only projected metadata and private project locators, never conversation text, arguments or transcript paths',async t=>{const home=fixture(t);write(home,'one',content('one')+line('response_item',{type:'function_call',name:'functions.exec',arguments:'node --test fixture.cjs; RAW_ARGUMENT_MARKER'}));const snapshot=await finish(metrics(home));const dir=path.join(home,'cache',fs.readdirSync(path.join(home,'cache'))[0]);const saved=fs.readFileSync(path.join(dir,'results.json'),'utf8');a.doesNotMatch(saved,/RAW_ARGUMENT_MARKER|Build the|payload|arguments|message\.content|rollout-|\.jsonl/);const rootRecords=JSON.parse(saved).entries[0][1].value.metadata.privateProjectRoots;a.equal(rootRecords.length,1);a.match(rootRecords[0].folder.replace(/\\/g,'/'),/\/projects\/Game$/);const contains=x=>x&&typeof x==='object'?Object.values(x).some(contains):x===rootRecords[0].folder;a.equal(contains(snapshot),false);a.doesNotMatch(JSON.stringify(snapshot),/privateProjectRoots/);a.doesNotMatch(saved,/GAME MENU/);a.match(saved,/projectName/);});
test('a corrupt cache falls back to reading the conversation',async t=>{const home=fixture(t);write(home,'one',content('one'));await finish(metrics(home));const dir=path.join(home,'cache',fs.readdirSync(path.join(home,'cache'))[0]);fs.writeFileSync(path.join(dir,'results.json'),'{bad');const s=await finish(metrics(home));a.equal(s.totals.tokens,10);a.equal(s.cache.hits,0);});
test('large conversations read only the opening and ending windows',async t=>{const home=fixture(t);const start=content('large'),middle=line('ignored',{text:'MIDDLE_ONLY_MARKER'+'x'.repeat(1800)}).repeat(2000),end=line('response_item',{type:'function_call',name:'functions.exec',arguments:'node --test last.cjs'})+line('event_msg',{type:'token_count',info:{total_token_usage:{total_tokens:900,input_tokens:800,output_tokens:100,cached_input_tokens:0}}},'2030-01-07T12:00:00Z');write(home,'large',start+middle+end);const original=fs.promises.open;let bytes=0;fs.promises.open=async(file,...args)=>{const h=await original(file,...args);if(String(file).endsWith('.jsonl')){const old=h.read.bind(h);h.read=async(...args)=>{const r=await old(...args);bytes+=r.bytesRead;return r;};}return h;};try{const s=await finish(metrics(home));a.ok(bytes<768*1024,'Read '+bytes+' bytes');a.equal(s.totals.tokens,900);a.equal(s.sessions[0].taskTitle,null);a.equal(s.sessions[0].action,'Running a command');a.doesNotMatch(JSON.stringify(s),/last\.cjs|GAME MENU/);a.equal(s.sessions[0].sampled,true);}finally{fs.promises.open=original;}});
test('finished independent portraits appear before any final totals',async t=>{const home=fixture(t);write(home,'recent',content('recent'));write(home,'older',content('older').repeat(20),86400001);const m=metrics(home,{scopeDays:3,limits:{entries:512,bytes:600,milliseconds:100}});await m.setScopeDays(3);let seen=false;for(let n=0;n<40;n++){await m.refresh();const s=m.snapshot();if(s.pending&&s.previewSessions.length){a.equal(s.totals.tokens,null);a.equal(s.counts.active,0);a.equal(s.ready,false);seen=true;break;}if(!s.pending)break;}a.equal(seen,true);await finish(m);});
test('tool types produce plain current actions and short file names',()=>{a.deepEqual(actionOf('Bash','pwd'),['Running a command','Rodando um comando']);a.deepEqual(actionOf('Write','/project/view.css'),['Editing view.css','Editando view.css']);a.deepEqual(actionOf('Read','/project/main.js'),['Reading main.js','Lendo main.js']);a.deepEqual(actionOf('Agent','review'),['Calling a helper','Chamando um ajudante']);a.deepEqual(actionOf('WebSearch','foo'),['Searching the web','Pesquisando na web']);a.equal(H.forbidden('Reading main.js'),false);a.equal(H.forbidden('js'),true);});
test('same names use distinguishing words or collapse to one multiplied portrait',()=>{const d=R.decorate([{id:'a',taskTitle:'GAME',taskWords:['GAME','MENU'],state:'recent'},{id:'b',taskTitle:'GAME',taskWords:['GAME','JUMP'],state:'recent'}],{},+now),g=R.group(d);a.equal(g.length,2);a.notEqual(g[0].title,g[1].title);const same=R.group(R.decorate([{id:'a',taskTitle:'GAME',state:'recent'},{id:'b',taskTitle:'GAME',state:'recent'},{id:'c',taskTitle:'GAME',state:'recent'}],{},+now));a.equal(same.length,1);a.equal(same[0].memberCount,3);a.doesNotMatch(same[0].title,/SECOND|THIRD|\d/);});
test('stale activity waits, without repeating the task name',()=>{const r=R.decorate([{id:'old',taskTitle:'PANEL',updated:'2030-01-07T11:49:00Z',state:'resting'}],{},+now)[0];a.equal(r.action,'Waiting');a.equal(r.actionPT,'Esperando');});
