'use strict';
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{EventEmitter}=require('node:events');
const {TaskBoard,decisions}=require('../src/lib/task-board.cjs'),R=require('../public/r4-core.js'),M=require('../public/r9-model.js'),H=require('../public/human.js');
function fixture(t){const home=fs.mkdtempSync(path.join(os.tmpdir(),'panel-r9-board-'));t.after(()=>{a.ok(path.resolve(home).startsWith(path.resolve(os.tmpdir())+path.sep+'panel-r9-board-'));fs.rmSync(home,{recursive:true,force:true});});return home;}
const now=Date.parse('2030-01-07T12:00:00Z');
test('the first partial snapshot reaches the current views without invoking the retired hero',()=>{const vm=require('node:vm'),source=fs.readFileSync('public/panel.js','utf8'),body=source.slice(source.indexOf('function render()'),source.indexOf('async function refresh(')),nodes=new Map(),calls=[];const $=id=>{if(id==='pipeline'||id==='claude-ring')throw Error('Retired hero accessed');if(!nodes.has(id))nodes.set(id,{replaceChildren(){},append(){},setAttribute(){}});return nodes.get(id);};const data={example:false,tasks:[],queue:[],usage:{ready:false,pending:true,sessions:[],progress:{done:0,total:17}}};const context={data,lang:'en',filterOwner:'',t:k=>k,$,el:()=>({setAttribute(){}}),document:{documentElement:{},querySelectorAll:()=>[]},renderBoard:()=>calls.push('board'),PanelV2:{render:value=>calls.push(value)},PanelWelcome:{render:value=>calls.push(value)},DuSync:{update:value=>calls.push(value)}};vm.runInNewContext(body+';render();',context);a.deepEqual(calls.slice(1),[data,data,data]);a.equal(context.document.documentElement.lang,'en');});
test('a failed first paint still schedules the next reader update instead of waiting thirty seconds',async()=>{const vm=require('node:vm'),source=fs.readFileSync('public/panel.js','utf8'),body=source.slice(source.indexOf('async function refresh('),source.indexOf('$("language").onchange')),scheduled=[];const context={busy:false,previous:null,data:null,example:false,fetch:async()=>({ok:true,json:async()=>({tasks:[],usage:{pending:true,scanning:true}})}),render:()=>{throw Error('Controlled first paint failure');},setTimeout:(fn,ms)=>scheduled.push(ms),$:()=>({}),t:k=>k};vm.createContext(context);vm.runInContext(body,context);await context.refresh();a.deepEqual(scheduled,[1000]);a.equal(context.busy,false);});
test('an incomplete saved board is ignored rather than turning a connection error into zero',t=>{const home=fixture(t),dir=path.join(home,'.panel-cache');fs.mkdirSync(dir);fs.writeFileSync(path.join(dir,'task-board.json'),JSON.stringify({version:1,folder:null}));a.equal(new TaskBoard(home).snapshot().board.connected,false);});
test('unconnected task folders report connection state, never manufactured deliveries or decisions',t=>{const b=new TaskBoard(fixture(t),{clock:()=>new Date(now)}),s=b.snapshot();a.equal(s.board.connected,false);a.equal(s.deliveries.connected,false);a.deepEqual(s.tasks,[]);a.deepEqual(s.deliveries.items,[]);a.equal(s.configured,false);});
test('dated real task completions are idempotent, exclude helpers, and persist when tasks leave the current folder',t=>{const home=fixture(t),folder=path.join(home,'tasks');fs.mkdirSync(folder);const text=(id,helper=false)=>`---\nid: ${id}\nphase: done\ncompleted_at: 2030-01-07T10:00:00Z\nhelper: ${helper}\n---\n# Fix the game jump\n`;fs.writeFileSync(path.join(folder,'one.md'),text('one'));fs.writeFileSync(path.join(folder,'same.md'),text('one'));fs.writeFileSync(path.join(folder,'helper.md'),text('helper',true));fs.writeFileSync(path.join(folder,'undated.md'),'---\nid: undated\nphase: done\n---\n# Old task\n');const b=new TaskBoard(home,{clock:()=>new Date(now)});a.equal(b.connect(folder).deliveries.items.length,1);a.equal(b.snapshot().deliveries.items.length,1);fs.unlinkSync(path.join(folder,'one.md'));fs.unlinkSync(path.join(folder,'same.md'));const restored=new TaskBoard(home,{clock:()=>new Date(now)});a.equal(restored.snapshot().deliveries.items.length,1);a.doesNotMatch(JSON.stringify(restored.snapshot()),new RegExp(home.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});
test('plain decision headings connect without counting them as completed tasks',t=>{const home=fixture(t),folder=path.join(home,'decisions');fs.mkdirSync(folder);fs.writeFileSync(path.join(folder,'decisions.md'),'# Decisions\n## 1. Choose game music\n## 2. Review game art\n## 3. DONE Previous choice\n');const b=new TaskBoard(home,{clock:()=>new Date(now)}),s=b.connect(folder);a.equal(s.tasks.length,2);a.ok(s.tasks.every(x=>x.needsOwner));a.equal(s.deliveries.items.length,0);a.equal(decisions('## 1. {"pageId":null}').length,0);});
test('folder errors retain an error state instead of an authoritative zero',t=>{const home=fixture(t),folder=path.join(home,'board');fs.mkdirSync(folder);const b=new TaskBoard(home);b.connect(folder);fs.rmdirSync(folder);const s=b.snapshot();a.equal(s.board.status,'error');a.equal(s.board.connected,false);a.equal(s.deliveries.connected,false);});
test('estimates remain anchored after expiry and across readings; relative copy says late',()=>{const agent={id:'anchored-r9',startedAt:'2030-01-07T11:00:00Z',taskDurationsMinutes:[10,20,30],updated:'2030-01-07T11:10:00Z',tokens:100};const f=R.forecast(agent,now);a.equal(f.at,Date.parse('2030-01-07T11:20:00Z'));a.equal(R.forecast({...agent,updated:'2030-01-07T12:30:00Z',tokens:500},now+3600000).at,f.at);a.match(M.relative(f,'pt',now),/^atrasada ~40 min/);a.match(M.relative({at:now-1000,method:'declared'},'en',now),/^late by ~1 min/);const declared=R.forecast({id:'declared',deadlineAt:'2030-01-07T11:50:00Z'},now);a.equal(declared.method,'declared');a.equal(declared.at,Date.parse('2030-01-07T11:50:00Z'));});
test('credit compares remaining percentage in the identified window, never tokens; prefers the weekly window',()=>{const u={updated:'2030-01-07T12:00:00Z',claude:{tokens:1e9,windows:[]},codex:{windows:[{minutes:300,used:10,reset:'2030-01-07T13:00:00Z'},{minutes:10080,used:62,reset:'2030-01-14T12:00:00Z'}]}};a.equal(M.credit(u,'claude').available,false);a.equal(M.credit(u,'codex').remaining,38);a.equal(M.credit(u,'codex').minutes,10080);a.equal(M.credit({...u,codex:{windows:[{used:20,reset:'bad'}]}},'codex').available,false);});
test('hierarchy uses only exact declared links, keeps unlinked work separate, and rejects cycles',()=>{const nodes=[{id:'owner',sessionKey:'proof'},{id:'child',parentKey:'proof'},{id:'unknown',projectId:'same'},{id:'cycle1',parentId:'cycle2'},{id:'cycle2',parentId:'cycle1'}],graph=M.hierarchy(nodes);a.equal(graph.edges.get('child'),'owner');a.equal(graph.edges.size,1);a.equal(graph.children('owner')[0].id,'child');a.ok(graph.unlinked.some(x=>x.id==='unknown'));});
test('names contain task words without helper/report tags and current action never copies the subject',()=>{const list=R.decorate([{id:'labels',role:'reviewer',taskTitle:'REVIEW GAME MENU HELPER REPORT',action:'REVIEW GAME MENU',projectName:'Game',lastTool:'Read',state:'working'}],{},now);a.doesNotMatch(list[0].title,/HELPER|REPORT|AJUDANTE/);a.notEqual(list[0].action,'REVIEW GAME MENU');a.equal(H.forbidden(list[0].title+' '+list[0].action),false);});
test('preference APIs require local Origin and validate scope without opening a second server',async t=>{const {createServer}=require('../src/panel.cjs'),home=fixture(t);let days=1;const metrics={setScopeDays:async value=>{if(![1,3,7].includes(value))throw RangeError();days=value;},get scopeDays(){return days;}};const server=createServer({base:home,metrics});server.address=()=>({port:3265});async function request(origin,n){return new Promise(resolve=>{const req=new EventEmitter();Object.assign(req,{url:'/api/scope',method:'POST',headers:{host:'127.0.0.1:3265',origin}});const res={writeHead(status){this.status=status;},end(body){resolve({status:this.status,body:JSON.parse(body)});}};server.emit('request',req,res);req.emit('data',JSON.stringify({days:n}));req.emit('end');});}a.equal((await request('http://evil.invalid',3)).status,403);a.equal(days,1);a.equal((await request('http://127.0.0.1:3265',3)).status,200);a.equal(days,3);a.equal((await request('http://127.0.0.1:3265',2)).status,400);});
