const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const pool=require('../public/dus.json');
function crew(saved={}){const ctx={DuPortraits:pool,localStorage:{getItem:()=>JSON.stringify(saved),setItem(k,v){Object.assign(saved,JSON.parse(v));}},module:{exports:{}}};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../public/crew.js'),'utf8'),ctx);return ctx.module.exports;}
test('24 distinct real thumbnails are embedded and decoded dimensions match',()=>{a.equal(pool.length,24);a.equal(new Set(pool.map(x=>x.id)).size,24);const hashes=new Set();for(const p of pool){a.ok(Number.isSafeInteger(p.id));a.equal(p.image,'/dus/'+p.id+'.png');const bytes=fs.readFileSync(path.join(__dirname,'../public',p.image));a.equal(bytes.readUInt32BE(16),96);a.equal(bytes.readUInt32BE(20),96);hashes.add(require('node:crypto').createHash('sha256').update(bytes).digest('hex'));}a.equal(hashes.size,24);});
test('portraits are different per active session and stable when reordered or added',()=>{const api=crew(),list=Array.from({length:24},(_,i)=>({id:'session-'+i,agent:i%2?'codex':'claude'}));const first=api.assign(list);a.equal(new Set(first.map(x=>x.du.id)).size,24);const reverse=api.assign([...list].reverse());const map=new Map(first.map(x=>[x.id,x.du.id]));a.ok(reverse.every(x=>map.get(x.id)===x.du.id));a.ok(first.every(x=>/^Du /.test(x.title)&&!/(?:CODEX|CLAUDE) \d/.test(x.title)));});
test('generic role labels follow explicit role and observed tool categories',()=>{const api=crew();a.equal(api.role({role:'reviewer',tools:[{name:'apply_patch'}]}),'reviewer');a.equal(api.role({tools:[{name:'view_image'}]}),'designer');a.equal(api.role({tools:[{name:'web__search'}]}),'researcher');a.equal(api.role({tools:[{name:'apply_patch'}]}),'dev');a.equal(api.role({tools:[]}),'creator');});
test('public feeding caps daily awards and never claims agent usage',()=>{const api=require('../public/tips.js');const snapshot={public:true,feeding:{tips:[{id:'basic',raridade:'comum',en:{titulo:'Basic',colar:'Check the result'},pt:{titulo:'Básico',colar:'Confira o resultado'}}]}};const now=new Date('2026-09-30T12:00:00Z');const first=api.publicFeed(snapshot,null,'basic',now),again=api.publicFeed(snapshot,first.saved,'basic',now);a.equal(first.gained,10);a.equal(again.gained,0);a.equal(first.model.collected.length,1);a.equal(first.model.tips[0].eatenForReal,false);const injected=api.publicModel(snapshot,{xp:99999,days:{'2099-01-01':['basic'],'2026-09-30':['unknown','basic','basic']}},now);a.equal(injected.model.xp,10);});
test('lofi waits 45s and supports reserve without external preload',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/lofi.js'),'utf8');a.ok(source.includes('45000'));a.ok(source.includes('radioIndex++'));a.ok(source.includes("root.navigator?.onLine"));a.ok(source.includes("event.source === frame.contentWindow"));a.ok(!source.includes('createElement(\'script\')'));});
test('private feeding endpoint is absent from the public build',()=>{const source=fs.readFileSync(path.join(__dirname,'../public/tips.js'),'utf8');a.ok(!source.includes('/api/alimentar'));a.ok(!source.includes('X-Painel-Nonce'));});
