'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),vm=require('node:vm');
const {createServer}=require('../src/panel.cjs');
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
function movie(){const header=Buffer.alloc(100);header.writeUInt32BE(1000,12);header.writeUInt32BE(2400,16);function box(kind,body){const h=Buffer.alloc(8);h.writeUInt32BE(body.length+8);h.write(kind,4);return Buffer.concat([h,body]);}return Buffer.concat([box('ftyp',Buffer.from('isom0000isom')),box('moov',box('mvhd',header))]);}
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tutorial264-composition-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const publicDir=path.join(dir,'public');fs.mkdirSync(path.join(publicDir,'tutorial-painel'),{recursive:true});const video=movie(),subtitle=Buffer.from('WEBVTT\n\n00:00.000 --> 00:02.000\nSynthetic local captions.\n');const videoSrc='/tutorial-painel/fixture.pt.mp4',subtitleSrc='/tutorial-painel/fixture.pt.vtt';fs.writeFileSync(path.join(publicDir,videoSrc),video);fs.writeFileSync(path.join(publicDir,subtitleSrc),subtitle);return {dir,publicDir,video,subtitle,videoSrc,subtitleSrc,release:{locale:'pt',videoSrc,subtitleSrc,approval:{approvedByOwner:true,approvedAtUtc:'2026-10-03T00:00:00Z',videoSha256:hash(video),subtitleSha256:hash(subtitle)}}};}
async function server(t,f,tutorialOptions){const instance=createServer({demoOnly:true,offline:true,profile:f.dir,tutorialOptions});await new Promise(resolve=>instance.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>instance.close(resolve)));return suffix=>fetch('http://127.0.0.1:'+instance.address().port+suffix);}
async function manifest(get){const response=await get('/tutorial-manifest.js');assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');assert.match(response.headers.get('content-type'),/^text\/javascript; charset=utf-8$/);const context={window:{}};vm.runInNewContext(await response.text(),context);return JSON.parse(JSON.stringify(context.window.PanelTutorialManifest));}
test('served composition loads local tutorial before both renderers and stays closed by default',async t=>{const f=fixture(t),get=await server(t,f);assert.deepEqual(await manifest(get),{version:1,tutorials:{}});const html=await (await get('/')).text();const scripts=[...html.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]);for(const renderer of ['/welcome.js','/onboarding22.js'])assert.ok(scripts.indexOf('/tutorial264.js')<scripts.indexOf(renderer));assert.ok(scripts.indexOf('/tutorial-manifest.js')<scripts.indexOf('/tutorial264.js'));assert.match(html,/href="\/tutorial264.css"/);for(const asset of ['/tutorial264.js','/tutorial264.css'])assert.equal((await get(asset)).status,200);assert.equal((await get(f.videoSrc)).status,404);assert.equal((await get(f.subtitleSrc)).status,404);});
test('existing local media without matching approval stays unavailable over HTTP',async t=>{const f=fixture(t),get=await server(t,f,{publicDir:f.publicDir,releases:[{...f.release,approval:undefined}]});assert.deepEqual(await manifest(get),{version:1,tutorials:{}});assert.equal((await get(f.videoSrc)).status,404);});
test('fresh manifests and media responses stop exposing an altered or removed fixture',async t=>{const f=fixture(t),get=await server(t,f,{publicDir:f.publicDir,releases:[f.release]});let value=await manifest(get);assert.equal(value.tutorials.pt.durationSeconds,2.4);assert.equal(value.tutorials.en,undefined);assert.equal(value.tutorials.es,undefined);for(const [src,bytes,type] of [[f.videoSrc,f.video,'video/mp4'],[f.subtitleSrc,f.subtitle,'text/vtt; charset=utf-8']]){const response=await get(src);assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');assert.equal(response.headers.get('content-type'),type);assert.deepEqual(Buffer.from(await response.arrayBuffer()),bytes);}assert.equal((await get('/tutorial-painel/unapproved.pt.mp4')).status,404);fs.appendFileSync(path.join(f.publicDir,f.subtitleSrc),'\nNOTE changed\n');assert.deepEqual(await manifest(get),{version:1,tutorials:{}});assert.equal((await get(f.videoSrc)).status,404);assert.equal((await get(f.subtitleSrc)).status,404);fs.writeFileSync(path.join(f.publicDir,f.subtitleSrc),f.subtitle);fs.unlinkSync(path.join(f.publicDir,f.videoSrc));assert.deepEqual(await manifest(get),{version:1,tutorials:{}});assert.equal((await get(f.videoSrc)).status,404);});
