'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createServer}=require('../src/panel.cjs');
const {exampleFor}=require('../src/lib/examples.cjs');
const example=require('../example.json');
test('solo example is isolated and leaves the larger fixture unchanged',()=>{const before=JSON.stringify(example),solo=exampleFor(example,'solo');assert.equal(solo.example,true);assert.equal(solo.exampleSize,'solo');assert.equal(solo.usage.sessions.length,2);assert.equal(JSON.stringify(example),before);assert.ok(exampleFor(example,'large').usage.sessions.length>=solo.usage.sessions.length);});
test('public panel serves assets and examples with an empty profile; phases cannot skip or accept foreign origins',async()=>{
  const profile=fs.mkdtempSync(path.join(os.tmpdir(),'panel-public-'));
  const server=createServer({base:profile,profile,demoOnly:true,metrics:{snapshot:()=>({sessions:[],ready:true})}});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
  try{
    for(const asset of ['/','/v21.js','/v21.css','/welcome.js','/acelerador/acelerador.js','/acelerador/acelerador.css'])assert.equal((await fetch(base+asset)).status,200,asset);
    const solo=await(await fetch(base+'/api/status?example=1&size=solo')).json();assert.equal(solo.usage.sessions.length,2);assert.equal(solo.exampleSize,'solo');
    const initial=await(await fetch(base+'/api/acelerador')).json();assert.equal(initial.modo,'publico');assert.equal(Object.keys(initial.fases).length,0);
    const post=(endpoint,body,origin=base)=>fetch(base+'/api/acelerador/'+endpoint,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','x-acelerador-token':initial.token},body:JSON.stringify(body)});
    assert.equal((await post('ligar',{fase:1},'http://example.invalid')).status,403);
    assert.equal((await post('ligar',{fase:2})).status,409);
    assert.equal((await post('ligar',{fase:1})).status,200);
    assert.equal((await post('minutos',{minutos:5})).status,200);
    const saved=await(await fetch(base+'/api/acelerador')).json();assert.equal(saved.minutos,5);assert.equal(Object.keys(saved.fases).length,1);
    assert.equal((await post('desfazer',{fase:2})).status,409);
    assert.equal((await post('desfazer',{fase:1})).status,200);
  }finally{await new Promise(r=>server.close(r));fs.rmSync(profile,{recursive:true,force:true});}
});

test('live projection ignores private conversation text and arguments and retains the proven parent',()=>{
  const {metadataStory,key}=require('../src/lib/session-story.cjs');
  const r=metadataStory(JSON.stringify({type:'response_item',timestamp:'2030-01-01T12:00:00Z',payload:{type:'function_call',name:'exec_command',arguments:'PRIVATE_CONTENT_MARKER'},parentSessionId:'parent'}));
  assert.equal(r.parentKey,key('parent'));assert.equal(JSON.stringify(r).includes('PRIVATE_CONTENT_MARKER'),false);assert.equal(r.taskTitle,undefined);
  const final=metadataStory({type:'response_item',timestamp:'2030-01-01T12:01:00Z',payload:{type:'message',role:'assistant',phase:'final_answer',content:'unfinished work'}},r);assert.equal(final.finishedAt,null);assert.ok(final.closedAt);
});

test('an empty real profile falls back to an identified example without configuration',async()=>{
  const {Metrics}=require('../src/lib/usage.cjs');const profile=fs.mkdtempSync(path.join(os.tmpdir(),'panel-empty-')),metrics=new Metrics(profile,{cacheDir:false,processReader:async()=>null});let server;
  try{for(let n=0;n<50;n++){await metrics.refresh();if(!metrics.pending&&!metrics.running)break;}clearTimeout(metrics.nextRound);server=createServer({base:profile,profile,metrics});await new Promise(r=>server.listen(0,'127.0.0.1',r));const result=await(await fetch('http://127.0.0.1:'+server.address().port+'/api/status')).json();assert.equal(result.example,true);assert.equal(result.fallback,true);assert.equal(result.exampleSize,'solo');}
  finally{clearTimeout(metrics.nextRound);if(server)await new Promise(r=>server.close(r));fs.rmSync(profile,{recursive:true,force:true});}
});

test('larger fictional team has a proven leader, nested helpers and keeps each helper inside its own AI, without affecting solo',()=>{const {hierarchy}=require('../public/r9-model.js');const large=exampleFor(example,'large'),graph=hierarchy(large.usage.sessions);assert.equal(large.usage.sessions.length,7);assert.equal(graph.roots.length,2);assert.ok(graph.roots.some(r=>r.role==='lead'));assert.equal(graph.edges.size,5);const byId=new Map(large.usage.sessions.map(s=>[s.id,s]));for(const [child,parent]of graph.edges)assert.equal(byId.get(child).agent,byId.get(parent).agent,'helper and parent share the AI');assert.equal(exampleFor(example,'solo').usage.sessions.length,2);});
test('example acceleration keeps all settings in memory and performs no profile reads',async()=>{const {createAcceleration}=require('../src/lib/acceleration.cjs'),http=require('node:http');const profile=fs.mkdtempSync(path.join(os.tmpdir(),'panel-example-phase-'));const acceleration=createAcceleration({folder:profile,persist:false}),server=http.createServer((req,res)=>acceleration.handle(req,res,new URL(req.url,'http://localhost')));await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const result=await(await fetch('http://127.0.0.1:'+server.address().port+'/api/acelerador')).json();assert.equal(result.modo,'publico');assert.deepEqual(fs.readdirSync(profile),[]);}finally{await new Promise(r=>server.close(r));fs.rmSync(profile,{recursive:true,force:true});}});

 test('public text assets negotiate gzip without altering their content',async()=>{const server=require('../src/panel.cjs').createServer({demoOnly:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const url='http://127.0.0.1:'+server.address().port+'/v21.js';const gzip=await fetch(url,{headers:{'accept-encoding':'gzip'}}),identity=await fetch(url,{headers:{'accept-encoding':'identity'}});assert.equal(gzip.headers.get('content-encoding'),'gzip');assert.equal(identity.headers.get('content-encoding'),null);assert.equal(await gzip.text(),await identity.text());}finally{await new Promise(r=>server.close(r));}});

test('reading source never claims a successful local reading for missing data or an example',()=>{const {readingSource}=require('../public/r9-model.js');for(const lang of ['en','pt','es']){const date='2030-01-01T12:00:00Z',none=readingSource(null,true,lang),example=readingSource({example:true,usage:{updated:date}},true,lang),missing=readingSource({example:false,usage:{updated:'invalid'}},true,lang),local=readingSource({example:false,usage:{updated:date}},true,lang);assert.equal(none.kind,'no successful reading');assert.equal(none.atUTC,null);assert.equal(example.kind,'example');assert.equal(example.atUTC,null);assert.match(example.message,/Fictional|fictício|ficticio/);assert.equal(missing.kind,'local time unavailable');assert.equal(missing.atUTC,null);assert.equal(local.kind,'last local reading');assert.equal(local.atUTC,'2030-01-01 12:00:00 UTC');assert.match(local.message,/2030-01-01 12:00:00 UTC/);}});

 test('Refresh confirms a new completed reading, never a fresh object from an unfinished scanner',()=>{const {refreshOutcome}=require('../public/r9-model.js'),previous={example:false,usage:{ready:true,updated:'2030-01-01T12:00:00Z',errors:0}},make=change=>({example:false,usage:{ready:true,updated:'2030-01-01T12:01:00Z',errors:0,...change}});assert.equal(refreshOutcome(previous,previous),'reading','cached locale or mode render is not a new response');assert.equal(refreshOutcome(make({scanning:true}),previous),'reading','new object still scanning');assert.equal(refreshOutcome(make({pending:true}),previous),'reading','new object still pending');assert.equal(refreshOutcome(make({pending:true,errors:1}),previous),'reading','scanner can retain earlier errors while running');for(const change of [{ready:false},{errors:1},{updated:'invalid'},{updated:previous.usage.updated},{updated:'2030-01-01T11:59:00Z'}])assert.equal(refreshOutcome(make(change),previous),'error','terminal response without completed new reading releases retry without success');assert.equal(refreshOutcome(make({}),previous),'success','new published time and ready state confirm completion');assert.equal(refreshOutcome(make({}),null),'success','first successful publication can confirm');assert.equal(refreshOutcome({example:true,usage:{}},previous),'success','fictional source has no local readAt');assert.equal(refreshOutcome({example:true,usage:{pending:true}},previous),'reading','unfinished example is not confirmed');assert.equal(refreshOutcome({example:true,usage:{errors:1}},previous),'error','example terminal error is not success');});

 test('Completed-task summary opens the selected dated task even when it completed yesterday',()=>{const vm=require('node:vm'),source=fs.readFileSync(path.join(__dirname,'../public/v21.js'),'utf8'),start=source.indexOf('function completedAccess(){'),end=source.indexOf('  function update(){',start);assert(start>=0&&end>start);const yesterday=new Date();yesterday.setUTCDate(yesterday.getUTCDate()-1);const selected={title:'Yesterday completed task',phase:{percent:100},completedAt:yesterday.toISOString()},today={title:'Different task from today',phase:{percent:100},completedAt:new Date().toISOString()};for(const lang of ['en','pt','es']){let opened;const value={textContent:selected.title,removeAttribute(){},setAttribute(){}};const context={lang,readingFailed:false,snapshot:{example:false,board:{connected:true,status:'ready'},tasks:[selected,today]},lines:{children:[{lastChild:value}]},title:t=>t.title,sourceNotes:()=>[],el:(tag,text)=>({tag,text}),root:{panelDrawer:(heading,body)=>opened={heading,body}},$:()=>({click(){throw Error('Must not delegate a historic task to today-only results');}})};vm.runInNewContext(source.slice(start,end)+';completedAccess();',context);assert.equal(value.tabIndex,0);value.onclick();assert.equal(opened.heading,selected.title);assert.equal(opened.body[0].text.endsWith(selected.completedAt.replace('T',' ').slice(0,19)+' UTC'),true);opened=null;let prevented=false;value.onkeydown({key:'Enter',preventDefault(){prevented=true;}});assert.equal(prevented,true);assert.equal(opened.heading,selected.title);}});
