'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('public/welcome.js','utf8');
function harness({lang='en',saved=null,failStorage=false}={}){
  const ids=new Map(),storage=new Map(saved?[['agent-panel-profile',JSON.stringify(saved)]]:[]),document={body:{dataset:{}},documentElement:{lang},activeElement:null};
  class Element{constructor(tag){this.tagName=tag;this.children=[];this.dataset={};this.attrs={};this.hidden=false;this.ownText='';}set id(id){this._id=id;ids.set(id,this);}get id(){return this._id;}set textContent(v){this.ownText=String(v);this.children=[];}get textContent(){return this.ownText+this.children.map(n=>n.textContent).join(' ');}append(...nodes){this.children.push(...nodes);}replaceChildren(...nodes){this.children=nodes;this.ownText='';}setAttribute(k,v){this.attrs[k]=v;}focus(){document.activeElement=this;}querySelectorAll(tag){return this.children.flatMap(n=>[...(n.tagName===tag?[n]:[]),...n.querySelectorAll(tag)]);}querySelector(selector){if(selector.startsWith('.'))return this.children.flatMap(n=>[n,...n.children]).find(n=>n.className===selector.slice(1));return this.querySelectorAll(selector)[0];}}
  document.createElement=tag=>new Element(tag);document.getElementById=id=>ids.get(id);for(const id of ['welcome','setup-guide','quit-panel','tab-home','main']){const n=new Element('div');n.id=id;}
  const selections=[],window={document,location:{search:'?lang='+lang},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>{if(failStorage)throw Error('Unavailable');storage.set(k,v);}},PanelV2:{select:v=>selections.push(v)},PanelClean:{setProfile:p=>window.profile=p}};
  vm.runInNewContext(source,{window,URLSearchParams});const host=ids.get('welcome');const click=text=>{const b=host.querySelectorAll('button').find(n=>n.textContent===text);assert.ok(b,text);b.onclick();};return{window,storage,host,click,selections};
}
test('first use chooses size and goal with exactly two choices',()=>{const h=harness();assert.equal(h.host.hidden,false);h.click('Just me');h.click('My next step');assert.equal(h.host.hidden,true);assert.equal(h.window.profile.mode,'beginner');assert.equal(h.window.profile.goal,'next');assert.equal(h.selections.at(-1),'home');});
test('small and large modes start on the chosen goal',()=>{for(const [size,mode,goal,view]of [['Small team','explorer','My team','team'],['Large project','pro','Usage and limits','usage']]){const h=harness();h.click(size);h.click(goal);assert.equal(h.window.profile.mode,mode);assert.equal(h.selections.at(-1),view);}});
test('skip is optional and persists, while reopening allows changing choices',()=>{const h=harness();h.click('Skip for now');const saved=JSON.parse(h.storage.get('agent-panel-profile'));assert.equal(saved.skipped,true);assert.equal(harness({saved}).host.hidden,true);h.window.PanelWelcome.show();assert.equal(h.host.hidden,false);h.click('Large project');h.click('My team');assert.equal(h.window.profile.mode,'pro');});
test('Portuguese and Spanish first use work when browser storage is unavailable',()=>{for(const [lang,size,goal]of [['pt','Só eu','Minha equipe'],['es','Solo yo','Mi equipo']]){const h=harness({lang,failStorage:true});h.click(size);h.click(goal);assert.equal(h.host.hidden,true);assert.equal(h.window.profile.mode,'beginner');}});
