'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {preparation,prepare,recordTeam}=require('./measurement-ready.cjs');
const profile={cpuSlowdown:4,latencyMs:150,downloadBytesPerSecond:200000,uploadBytesPerSecond:93750,isMobile:true,hasTouch:true,deviceScaleFactor:1,viewport:'375 × 812',fixtureResponseDelayMs:500};
async function checkPairs({browser,base,out}){
  const sample=await(await fetch(base+'/api/status?example=1&size=large')).json(),runs=[],errors=[];
  for(let pair=0;pair<3;pair++)for(const traced of pair%2?[true,false]:[false,true]){
    const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,deviceScaleFactor:1,reducedMotion:'no-preference'}),page=await context.newPage(),cdp=await context.newCDPSession(page);let responseMode='success';
    await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750,connectionType:'cellular3g'});
    await page.addInitScript(()=>{localStorage.setItem('agent-panel-profile',JSON.stringify({version:2,mode:'explorer',size:'large',goal:'finish'}));window.pairProbe={timing:[],network:[]};const map=e=>({name:e.name,targetId:e.target?.id||e.target?.dataset?.control||null,interactionId:e.interactionId,durationMs:e.duration,startTimeMs:e.startTime,inputDelayMs:e.processingStart-e.startTime,processingMs:e.processingEnd-e.processingStart,presentationDelayApproxMs:Math.max(0,e.startTime+e.duration-e.processingEnd)});new PerformanceObserver(l=>{for(const e of l.getEntries())if(e.interactionId)window.pairProbe.timing.push(map(e));}).observe({type:'event',buffered:true,durationThreshold:16});const original=window.fetch.bind(window);window.fetch=async(...args)=>{const u=new URL(typeof args[0]==='string'?args[0]:args[0].url,location.href);if(u.pathname!=='/api/status')return original(...args);const requestAtMs=performance.now(),response=await original(...args);window.pairProbe.network.push({path:u.pathname,requestAtMs,responseAtMs:performance.now(),status:response.status});return response;};});
    await page.route('**/api/status*',async r=>{const mode=responseMode;await new Promise(resolve=>setTimeout(resolve,500));await r.fulfill({status:mode==='error'?503:200,contentType:'application/json',body:JSON.stringify(mode==='error'?{error:'Synthetic metadata read failed'}:sample)});});
    const actions=[];let artifact=null,traceStarted=false;
    try{
      const baseline=await prepare(page,base,'normal');
      if(traced){await cdp.send('Tracing.start',{categories:'devtools.timeline,disabled-by-default-devtools.timeline.frame,disabled-by-default-devtools.screenshot,blink.user_timing',transferMode:'ReturnAsStream'});traceStarted=true;}
      async function action(name,selector,result){
        await page.evaluate(({name,selector,result})=>{window.pairReceipt=new Promise((resolve,reject)=>{let entry,stamp,ack=null;const timer=setTimeout(()=>{observer.disconnect();reject(Error('Missing semantic response: '+name));},5000),observer=new MutationObserver(()=>{if(entry===undefined)return;const status=document.querySelector('#clean-refresh-status');if(name!=='common'&&status?.dataset.state==='reading'&&ack===null){ack=performance.now();performance.mark('pair-'+name+'-reading');}const finished=name==='common'?document.body.dataset.view==='team':status?.dataset.state===result;if(finished){const at=performance.now();performance.mark('pair-'+name+'-result');observer.disconnect();clearTimeout(timer);resolve({name,selector,isTrusted:true,eventTimeStampMs:stamp,handlerEntryMs:entry,readingDOMAtMs:ack,resultDOMAtMs:at,eventToReadingDOMMs:ack===null?null:ack-stamp,eventToSemanticDOMMs:at-stamp,handlerToSemanticDOMMs:at-entry,drawerStillOpen:!!document.querySelector('#drawer')?.open,resultText:status?.textContent||'Team',escapeAtMs:null});}}),listener=e=>{if(!e.isTrusted||!e.target.closest(selector))return;document.removeEventListener('click',listener,true);entry=performance.now();stamp=e.timeStamp;performance.mark('pair-'+name+'-entry');};observer.observe(document.body,{attributes:true,childList:true,subtree:true});document.addEventListener('click',listener,true);});},{name,selector,result});
        await page.locator(selector).tap();const receipt=await page.evaluate(()=>window.pairReceipt);if(name!=='common'&&!receipt.drawerStillOpen)throw Error('Refresh must keep Preferences open');await page.waitForTimeout(100);return receipt;
      }
      const common=await action('common','#tab-team','team');common.contentEvidence=await recordTeam(page,out,'paired-'+(pair+1)+'-trace-'+(traced?'on':'off'));actions.push(common);await page.locator('#tab-home').tap();await page.locator('.clean-more>summary').tap();await page.locator('.clean-menu>button:not([data-view])').tap();responseMode='error';actions.push(await action('error','[data-control=refresh]','error'));responseMode='success';actions.push(await action('success','[data-control=refresh]','success'));
      const probe=await page.evaluate(()=>window.pairProbe);for(const a of actions){const target=a.name==='common'?'tab-team':'refresh',clicks=probe.timing.filter(e=>e.name==='click'&&e.targetId===target&&Math.abs(e.startTimeMs-a.eventTimeStampMs)<80),ids=new Set(clicks.map(e=>e.interactionId)),events=probe.timing.filter(e=>ids.has(e.interactionId)),byId=new Map();for(const e of events)byId.set(e.interactionId,Math.max(byId.get(e.interactionId)||0,e.durationMs));a.eventTiming=events;a.byInteractionId=[...byId].map(([interactionId,maxDurationMs])=>({interactionId,maxDurationMs}));a.maxObservedInteractionMs=byId.size?Math.max(...byId.values()):null;a.presentationDelayApproxMaxMs=events.length?Math.max(...events.map(e=>e.presentationDelayApproxMs)):null;a.network=probe.network.filter(e=>e.requestAtMs>=a.handlerEntryMs&&e.requestAtMs<=a.resultDOMAtMs);}
      let filmstrip=[],paintEvents=0,marks=[];
      if(traced){const complete=new Promise(r=>cdp.once('Tracing.tracingComplete',r));await cdp.send('Tracing.end');traceStarted=false;const {stream}=await complete;let raw='';for(;;){const c=await cdp.send('IO.read',{handle:stream});raw+=c.base64Encoded?Buffer.from(c.data,'base64').toString():c.data;if(c.eof)break;}await cdp.send('IO.close',{handle:stream});artifact='paired-'+(pair+1)+'-trace-on.json';fs.writeFileSync(path.join(out,artifact),raw);const events=JSON.parse(raw).traceEvents||[];filmstrip=events.filter(e=>e.name==='Screenshot'&&e.args?.snapshot).map(e=>({traceTimestampUs:e.ts,sha256:crypto.createHash('sha256').update(e.args.snapshot).digest('hex')}));paintEvents=events.filter(e=>/Paint|DrawFrame|Display::FrameDisplayed/.test(e.name)).length;marks=events.filter(e=>e.name?.startsWith('pair-')||e.name==='team-recorded-before-home').map(e=>({name:e.name,traceTimestampUs:e.ts}));if(!filmstrip.length||!paintEvents)throw Error('Traced pair lacks usable screenshots or paint events');}
      runs.push({pair:pair+1,traced,baseline,orderWithinPair:pair%2?(traced?1:2):(traced?2:1),actions,rawEventTiming:probe.timing,network:probe.network,artifact,filmstrip,paintEvents,marks,ok:true});
    }catch(e){errors.push({pair:pair+1,traced,message:e.message,stack:e.stack});runs.push({pair:pair+1,traced,actions,ok:false});}finally{if(traceStarted){try{await cdp.send('Tracing.end');}catch{}}await context.close();}
  }
  const summarize=values=>{const sorted=values.filter(Number.isFinite).sort((a,b)=>a-b);return{n:sorted.length,median:sorted.length?sorted[Math.floor(sorted.length/2)]:null,min:sorted[0]??null,max:sorted.at(-1)??null,samples:values};},summaries=[];
  for(const name of ['common','error','success'])for(const traced of [false,true]){const actions=runs.filter(r=>r.traced===traced).flatMap(r=>r.actions.filter(a=>a.name===name));summaries.push({action:name,traced,eventToSemanticDOMMs:summarize(actions.map(a=>a.eventToSemanticDOMMs)),maxObservedInteractionMs:summarize(actions.map(a=>a.maxObservedInteractionMs)),presentationDelayApproxMaxMs:summarize(actions.map(a=>a.presentationDelayApproxMaxMs)),readingAcknowledgmentDOMMs:summarize(actions.map(a=>a.eventToReadingDOMMs))});}
  const report={ok:errors.length===0&&runs.length===6,profile,preparation,systemReducedMotion:'no-preference',source:'Shipped fictional larger-team metadata; same fixed500 ms server fixture in both sides',flow:'Home→Team; collect common interaction latency; observe Team for1000 ms and take a late verification photograph on BOTH sides, including the control without tracing. Return Home, open Preferences, trusted Refresh503, then trusted Refresh200; wait for each accessible result with Preferences open. Only the trace side records a trace. The late photographs do not measure first presented-frame latency.',runs,summaries,errors,limitations:'Three paired runs per action are laboratory samples, not field p75. Event Timing uses maximum per interactionId, not sums. Empty observations remain unknown. DOM acknowledgment is not presentation; filmstrip causal frames require independent review. No visual100 ms claim is inferred from callback counts.'};fs.writeFileSync(path.join(out,'paired-comparison.json'),JSON.stringify(report,null,2)+'\n');return report;
}
module.exports={checkPairs};
