'use strict';
// Run in an isolated worker. Only fictional fixtures and an empty temporary profile are used.
// node tools/validate-public.cjs --playwright /path/to/playwright-core --browser /path/to/chromium
// OUTPUT_DIR chooses the artifact directory. PLAYWRIGHT_MODULE and CHROMIUM_PATH are optional alternatives.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'..');const args=process.argv.slice(2),value=flag=>args.includes(flag)?args[args.indexOf(flag)+1]:null;
const out=path.resolve(process.env.OUTPUT_DIR||value('--out')||path.join(ROOT,'validation-output'));fs.mkdirSync(out,{recursive:true});
async function main(){
  const tests=fs.readdirSync(path.join(ROOT,'test')).filter(x=>x.endsWith('.test.cjs')).map(x=>path.join(ROOT,'test',x));
  const result=spawnSync(process.execPath,['--test','--test-concurrency=1',...tests],{cwd:ROOT,encoding:'utf8',maxBuffer:16*1024*1024});
  fs.writeFileSync(path.join(out,'tests.txt'),(result.stdout||'')+(result.stderr||''));console.log('Test exit:',result.status);if(result.status!==0)console.log('Tests failed; captures will still run for review.');
  const playwright=require(value('--playwright')||process.env.PLAYWRIGHT_MODULE||'playwright-core'),browserPath=value('--browser')||process.env.CHROMIUM_PATH;
  const profile=fs.mkdtempSync(path.join(os.tmpdir(),'panel-capture-'));
  const {createServer}=require('../src/panel.cjs'),{Metrics}=require('../src/lib/usage.cjs');const metrics=new Metrics(profile,{cacheDir:false,processReader:async()=>null});for(let n=0;n<50;n++){await metrics.refresh();if(!metrics.pending&&!metrics.running)break;}clearTimeout(metrics.nextRound);const server=createServer({base:profile,profile,metrics});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;
  const captures=[],evidence=[],checks=[];const receipt={ok:false,captures,evidence,checks,testsExit:result.status,source:'Fictional teams, an empty real profile and synthetic metadata',labOnly:true};const save=()=>fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(receipt,null,2)+'\n');save();const shot=async(page,name)=>{await page.screenshot({path:path.join(out,name),fullPage:true});captures.push(name);save();};
  try{
    browser=await playwright.chromium.launch({headless:true,...(browserPath?{executablePath:browserPath}:{}),args:['--no-sandbox']});
    for(const locale of ['en','pt','es'])for(const width of [1440,768,390,375]){
      const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});await context.addInitScript(()=>{window.publicLab={lcp:null,cls:0,shifts:[]};try{new PerformanceObserver(list=>{for(const e of list.getEntries())window.publicLab.lcp=e.startTime;}).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(list=>{for(const e of list.getEntries())if(!e.hadRecentInput){window.publicLab.cls+=e.value;window.publicLab.shifts.push({atMs:e.startTime,value:e.value,sources:(e.sources||[]).map(s=>({node:s.node?.id||s.node?.tagName,previous:s.previousRect.toJSON(),current:s.currentRect.toJSON()}))});}}).observe({type:'layout-shift',buffered:true});}catch{}});const page=await context.newPage(),errors=[],consoleErrors=[],failedRequests=[],httpErrors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});page.on('requestfailed',r=>failedRequests.push(new URL(r.url()).pathname));page.on('response',r=>{if(r.status()>=400)httpErrors.push({path:new URL(r.url()).pathname,status:r.status()});});
      await page.goto(base+'/?example=1&size=large&lang='+locale);await page.waitForSelector('#home-stage .du-agent');await page.waitForFunction(()=>document.querySelector('#clean-active').textContent!=='?');
      await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(img=>img.complete?Promise.resolve():new Promise(r=>{img.addEventListener('load',r,{once:true});img.addEventListener('error',r,{once:true});})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});await page.waitForTimeout(200);const initialLab=await page.evaluate(()=>({...window.publicLab,windowEndedAtMs:performance.now(),scope:'Initial load until rendered content and assets settled, before scripted interaction'}));const initialEvidence={viewport:width,locale,initialLab};evidence.push(initialEvidence);save();assert.ok(initialLab.cls<=0.1,'Initial load CLS <= 0.1 at '+width+' '+locale+': '+JSON.stringify(initialLab));assert.equal(await page.locator('#clean-overview .clean-line').count(),6);assert.equal(await page.locator('#view-tabs [role=tab]').count(),4);
      for(const mode of ['beginner','explorer','pro']){await page.evaluate(mode=>window.PanelClean.setProfile({mode}),mode);const visible=await page.locator('#home-stage .du-agent:visible').count();assert.ok(mode!=='beginner'||visible<=2);assert.ok(mode!=='explorer'||visible<=6);}
      await page.evaluate(()=>window.PanelClean.setProfile({mode:'explorer'}));
      const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,'Horizontal overflow at '+width+' '+locale);
      const name='home-'+locale+'-'+width+'.png';await page.screenshot({path:path.join(out,name),fullPage:true});captures.push(name);
      for(const key of ['usage','projects']){await page.click('#tab-'+key);await page.locator('#view-'+key).waitFor({state:'visible'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'Overflow '+key);}
      await page.click('.clean-more > summary');await page.click('#tab-queue');await page.locator('#view-queue').waitFor({state:'visible'});
      await page.click('.clean-more > summary');await page.click('#tab-tips');await page.locator('#view-tips').waitFor({state:'visible'});
      await page.click('#tab-home');
      for(let i=0;i<2;i++){await page.click('.clean-more > summary');await page.getByRole('button',{name:locale==='pt'?'Preferências':locale==='es'?'Preferencias':'Preferences',exact:true}).click();await page.getByRole('button',{name:i?'EXPLORER':'BEGINNER',exact:true}).click();assert.equal(await page.locator('#clean-language').count(),1);await page.selectOption('#clean-language',locale);await page.click('#close-drawer');await page.click('#clean-wen');await page.click('#close-drawer');}
      await page.click('#clean-wen');assert.equal(await page.locator('#drawer').isVisible(),true);await page.click('#close-drawer');await page.click('#clean-auto');assert.equal(await page.locator('#drawer textarea').count(),1);await page.click('#close-drawer');
      await page.click('#acel-trigger');await page.locator('#acel-gaveta').waitFor({state:'visible'});await page.click('.acel-fechar');
      const switchStart=Date.now();await page.click('#tab-team');await page.waitForSelector('#look-team .look-node[data-type=session]');const switchMs=Date.now()-switchStart;assert.ok(await page.locator('#look-team .look-wire-hit[data-parent]:not([data-parent=""])').count()>0,'Known parent links are rendered');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'Team overflow');const team='team-'+locale+'-'+width+'.png';await page.screenshot({path:path.join(out,team),fullPage:true});captures.push(team);
      const overlap=await page.evaluate(()=>{const nodes=[...document.querySelectorAll('#view-tabs [role=tab],#clean-actions > button,#acel-trigger')].filter(n=>n.getClientRects().length);return nodes.some((a,i)=>nodes.slice(i+1).some(b=>{const x=a.getBoundingClientRect(),y=b.getBoundingClientRect();return Math.min(x.right,y.right)-Math.max(x.left,y.left)>1&&Math.min(x.bottom,y.bottom)-Math.max(x.top,y.top)>1;}));});assert.equal(overlap,false,'Overlapping controls');assert.deepEqual(errors,[],'Page errors');assert.deepEqual(consoleErrors,[],'Console errors');assert.deepEqual(failedRequests,[],'Failed requests');assert.deepEqual(httpErrors,[],'HTTP errors');
      const contrast=await page.locator('#clean-wen').evaluate(n=>{const css=getComputedStyle(n),channel=v=>{v/=255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)},lum=s=>{const c=s.match(/[\d.]+/g).slice(0,3).map(Number).map(channel);return .2126*c[0]+.7152*c[1]+.0722*c[2]};const a=lum(css.color),b=lum(css.backgroundColor);return {foreground:css.color,background:css.backgroundColor,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)};});assert.ok(contrast.ratio>=4.5,'WEN normal text contrast AA');const detail=await page.evaluate(()=>({title:document.title,language:document.documentElement.lang,source:document.querySelector('#clean-source').textContent,data:window.PanelClean.status(),statusRole:document.querySelector('#clean-source').getAttribute('role'),overflow:document.documentElement.scrollWidth>innerWidth+1,targets:[...document.querySelectorAll('#view-tabs [role=tab],#clean-actions > button,#acel-trigger')].map(n=>({label:n.textContent.trim(),height:Math.round(n.getBoundingClientRect().height)})),journeyLab:{...window.publicLab,scope:'Whole scripted journey, including programmatic mode changes; not initial-load CWV'}}));assert.ok(detail.targets.every(t=>t.height>=44),'Main control targets are at least 44px');Object.assign(initialEvidence,{viewport:width,locale,observedAtUTC:new Date().toISOString(),switchMs,contrast,initialLab,errors,consoleErrors,failedRequests,httpErrors,...detail});save();await context.close();
    }
    const context=await browser.newContext({viewport:{width:390,height:1000}}),page=await context.newPage();await page.goto(base+'/?lang=en');await page.locator('#welcome').waitFor({state:'visible'});await shot(page,'onboarding-size-en-390.png');await page.getByRole('button',{name:'Just me',exact:true}).click();await shot(page,'onboarding-goal-en-390.png');await page.getByRole('button',{name:'My next step',exact:true}).click();assert.equal(await page.locator('#welcome').isVisible(),false);assert.equal(await page.evaluate(()=>window.PanelClean.profile().mode),'beginner');await page.reload();assert.equal(await page.locator('#welcome').isVisible(),false);const empty=await(await fetch(base+'/api/status')).json();assert.equal(empty.fallback,true,'Empty isolated profile gets an identified example');assert.equal(empty.example,true,'Fallback remains explicitly fictional');await page.waitForSelector('#home-stage .du-agent');await shot(page,'empty-profile-en-390.png');checks.push({name:'First use',choices:2,skipAvailable:true,persistsAfterReload:true,emptyRealProfileFallback:true});await context.close();
    const skipped=await browser.newContext({viewport:{width:390,height:1000}}),skipPage=await skipped.newPage();await skipPage.goto(base+'/?lang=en');await skipPage.getByRole('button',{name:'Skip for now',exact:true}).click();assert.equal(await skipPage.locator('#welcome').isVisible(),false);await shot(skipPage,'onboarding-skipped-en-390.png');checks.push({name:'Skip first use',ok:true});await skipped.close();
    for(const locale of ['en','pt'])for(const width of [1440,390]){const solo=await browser.newContext({viewport:{width,height:1000}}),p=await solo.newPage();await p.goto(base+'/?example=1&size=solo&lang='+locale);await p.waitForSelector('#home-stage .du-agent');assert.equal(await p.locator('#home-stage .du-agent').count(),2);const name='solo-'+locale+'-'+width+'.png';await p.screenshot({path:path.join(out,name),fullPage:true});captures.push(name);await solo.close();}
    const fixtureDate=new Date().toISOString(),fixture=path.join(profile,'.codex','sessions','rollout-synthetic.jsonl');fs.mkdirSync(path.dirname(fixture),{recursive:true});fs.writeFileSync(fixture,[{type:'session_meta',timestamp:fixtureDate,payload:{id:'synthetic-session',cwd:'/example/tiny-game'}},{type:'turn_context',timestamp:fixtureDate,payload:{model:'gpt-6.1-sol',effort:'high'}},{type:'event_msg',timestamp:fixtureDate,payload:{type:'token_count',info:{total_token_usage:{total_tokens:12,input_tokens:10,output_tokens:2,cached_input_tokens:0}},rate_limits:{primary:{used_percent:37,window_minutes:300,resets_at:Math.floor(Date.now()/1000)+3600}}}}].map(r=>JSON.stringify(r)).join('\n')+'\n');
    for(let n=0;n<100;n++){await metrics.refresh();if(!metrics.pending&&!metrics.running)break;}clearTimeout(metrics.nextRound);const own=await(await fetch(base+'/api/status')).json();assert.equal(own.example,false,'Synthetic rollout must replace the empty-profile example');assert.equal(own.usage.sessions.length,1);assert.equal(own.usage.sessions[0].tokens,12);assert.equal(own.usage.sessions[0].projectName,'tiny-game');assert.equal(own.usage.sessions[0].taskTitle,null);
    const states=await browser.newContext({viewport:{width:390,height:1000}}),statePage=await states.newPage();await statePage.addInitScript(()=>localStorage.setItem('agent-panel-profile',JSON.stringify({version:2,mode:'beginner',size:'solo',goal:'next'})));await statePage.goto(base+'/?lang=en');await statePage.waitForFunction(()=>document.querySelector('#clean-active').textContent!=='?');assert.equal(await statePage.locator('#clean-source').textContent(),'Local reading');assert.match(await statePage.locator('#clean-overview').textContent(),/63% remaining/);assert.match(await statePage.locator('#clean-overview .clean-line').first().textContent(),/Tasks not connected/,'Missing task board is unknown, not an empty delivery list');checks.push({name:'Synthetic reading',source:'Local reading',readAtUTC:own.usage.updated,tokens:12,quotaRemainingPercent:63,taskTitleAvailable:false,tasksConnected:false});const realName='synthetic-en-390.png';await statePage.screenshot({path:path.join(out,realName),fullPage:true});captures.push(realName);
    const loading=await browser.newContext({viewport:{width:390,height:1000}}),loadPage=await loading.newPage();await loading.addInitScript(()=>localStorage.setItem('agent-panel-profile',JSON.stringify({version:2,mode:'beginner',size:'solo',goal:'next'})));let release;const delayed=new Promise(r=>release=r);await loadPage.route('**/api/status*',async route=>{await delayed;await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(own)});});await loadPage.goto(base+'/?lang=en',{waitUntil:'domcontentloaded'});await loadPage.waitForFunction(()=>!!window.PanelClean);assert.equal(await loadPage.locator('#clean-active').textContent(),'?','Initial loading is unknown');await shot(loadPage,'loading-en-390.png');release();await loadPage.waitForFunction(()=>document.querySelector('#clean-active').textContent!=='?');await loading.close();
    await statePage.route('**/api/status*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Synthetic unavailable reading'})}));await statePage.evaluate(()=>document.querySelector('#refresh').click());await statePage.waitForFunction(()=>document.querySelector('#clean-source').textContent.includes('not available'));assert.equal(await statePage.locator('#clean-active').textContent(),'?','A failed reading is unknown');await shot(statePage,'failure-en-390.png');checks.push({name:'Loading and failed reading',unknown:true,expectedSyntheticHTTP:503,photos:true});
    await statePage.click('#clean-wen');assert.equal(await statePage.evaluate(()=>document.activeElement.id),'close-drawer','Drawer focuses its close control');await statePage.keyboard.press('Tab');assert.equal(await statePage.evaluate(()=>document.activeElement.id),'close-drawer','WEN dialog retains keyboard focus');await shot(statePage,'keyboard-focus-en-390.png');await statePage.keyboard.press('Escape');assert.equal(await statePage.locator('#drawer').isVisible(),false,'Esc closes WEN');await statePage.locator('#tab-home').focus();await statePage.keyboard.press('ArrowRight');assert.equal(await statePage.evaluate(()=>document.body.dataset.view),'team','Right arrow selects Team');checks.push({name:'Keyboard',drawerFocus:true,tabWithinDialog:true,escapeCloses:true,arrowTabs:true});await states.close();
    const motion=await browser.newContext({viewport:{width:390,height:1000},reducedMotion:'no-preference'}),motionPage=await motion.newPage();await motionPage.goto(base+'/?example=1&size=large&lang=en');await motionPage.waitForSelector('#home-stage .du-agent');await motionPage.click('.clean-more > summary');await motionPage.getByRole('button',{name:'Preferences',exact:true}).click();await motionPage.locator('#drawer-body').getByRole('button',{name:'Motion',exact:true}).click();assert.equal(await motionPage.evaluate(()=>document.documentElement.dataset.motion),'off','Product Motion off is enabled');assert.equal(await motionPage.evaluate(()=>localStorage.getItem('agent-panel-motion')),'off','Motion off is saved');await motionPage.click('#close-drawer');await motionPage.reload();await motionPage.waitForSelector('#home-stage .du-agent');assert.equal(await motionPage.evaluate(()=>document.documentElement.dataset.motion),'off','Motion off survives reload');const animations=await motionPage.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length);assert.equal(animations,0,'Motion off has no running document animations');await shot(motionPage,'motion-off-en-390.png');checks.push({name:'Product Motion off',reducedMotionPreference:'no-preference',persists:true,runningAnimations:animations});await motion.close();
    const focused=await require('./validate-focused.cjs').runFocused({browser,base,out,own,empty,onProgress:partial=>{receipt.focusedPartial=partial;save();}});captures.push(...focused.captures);checks.push(...focused.checks);
    fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify({ok:result.status===0,captures,checks,testsExit:result.status,source:'Fictional teams, an empty real profile and synthetic metadata',evidence,labOnly:true},null,2)+'\n');console.log('Captured',captures.length,'screens.');if(result.status!==0)process.exitCode=1;
  }catch(error){receipt.failed=error.stack||error.message;save();throw error;}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));fs.rmSync(profile,{recursive:true,force:true});}
}
main().catch(error=>{console.error(error.stack||error.message);process.exitCode=1;});
