'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const settled=page=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
async function runFocused({browser,base,out,own,empty,onProgress=()=>{}}){
  const captures=[],checks=[];const report=()=>onProgress({captures,checks}),add=entry=>{checks.push(entry);report();};const shot=async(p,n)=>{await p.screenshot({path:path.join(out,n),fullPage:true});captures.push(n);report();};
  for(const width of [375,1440]){
    const context=await browser.newContext({viewport:{width,height:1000}}),p=await context.newPage();let response=empty,hold=null;
    await p.route('**/api/status*',async route=>{if(hold)await hold;if(response===null)return route.fulfill({status:503,contentType:'application/json',body:'{"error":"Synthetic unavailable reading"}'});return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(response)});});
    await p.goto(base+'/?lang=en');await p.locator('#welcome').waitFor({state:'visible'});await shot(p,'onboarding-size-en-'+width+'.png');await p.getByRole('button',{name:'Just me',exact:true}).click();await shot(p,'onboarding-goal-en-'+width+'.png');await p.getByRole('button',{name:'My next step',exact:true}).click();await p.waitForSelector('#home-stage .du-agent');await shot(p,'empty-profile-en-'+width+'.png');
    response=own;await p.reload();await p.waitForFunction(()=>document.querySelector('#clean-source').textContent==='Local reading');await shot(p,'synthetic-en-'+width+'.png');
    let release;hold=new Promise(r=>release=r);await p.goto(base+'/?lang=en',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>!!window.PanelClean);assert.equal(await p.locator('#clean-active').textContent(),'?','Loading remains unknown at '+width);await shot(p,'loading-en-'+width+'.png');release();hold=null;await p.waitForFunction(()=>document.querySelector('#clean-active').textContent!=='?');
    response=null;await p.evaluate(()=>document.querySelector('#refresh').click());await p.waitForFunction(()=>document.querySelector('#clean-source').textContent.includes('not available'));await shot(p,'failure-en-'+width+'.png');
    await p.click('#clean-wen');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.id),'close-drawer','Single-control modal focus at '+width);await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.id),'close-drawer','Reverse modal focus at '+width);await shot(p,'keyboard-focus-en-'+width+'.png');await p.keyboard.press('Escape');assert.equal(await p.locator('#drawer').isVisible(),false,'Escape closes modal');add({name:'States and keyboard',width,provider:'Recorded fictional empty profile and synthetic metadata',loading:true,error:true,forwardAndReverseTab:true,escape:true});await context.close();
  }
  const context=await browser.newContext({viewport:{width:375,height:1000},reducedMotion:'no-preference'}),p=await context.newPage(),wire=[];
  await context.addInitScript(()=>{window.publicProbe={frames:[],shifts:[],inputs:[],mediaPlayCalls:0,audioContexts:0};const tick=t=>{if(window.publicProbe.frames.length<10000)window.publicProbe.frames.push(t);requestAnimationFrame(tick);};requestAnimationFrame(tick);document.addEventListener('click',e=>{if(!e.isTrusted)return;const b=e.target.closest('button');if(!b)return;const record={label:b.textContent.trim(),inputAtMs:performance.now(),nextFrameAtMs:null};window.publicProbe.inputs.push(record);requestAnimationFrame(t=>record.nextFrameAtMs=t);},true);new PerformanceObserver(list=>{for(const e of list.getEntries())if(!e.hadRecentInput)window.publicProbe.shifts.push({atMs:e.startTime,value:e.value,sources:(e.sources||[]).map(s=>({node:s.node?.id||s.node?.tagName,previous:s.previousRect.toJSON(),current:s.currentRect.toJSON()}))});}).observe({type:'layout-shift',buffered:true});const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(...args){window.publicProbe.mediaPlayCalls++;return play.apply(this,args);};if(window.AudioContext){const Original=window.AudioContext;window.AudioContext=new Proxy(Original,{construct(Target,args){window.publicProbe.audioContexts++;return Reflect.construct(Target,args);}});}});
  p.on('response',async r=>{if(new URL(r.url()).origin!==base)return;try{const body=await r.body(),h=await r.allHeaders();wire.push({path:new URL(r.url()).pathname,status:r.status(),decodedBytes:body.length,wireBytes:h['content-length']?Number(h['content-length']):null,encoding:h['content-encoding']||'identity',type:h['content-type']||''});}catch{}});
  await p.goto(base+'/?example=1&size=large&lang=en');await p.waitForSelector('#home-stage .du-agent');await settled(p);const initialWire=wire.slice();await p.evaluate(()=>{for(const n of document.querySelectorAll('.brand,footer a[href*="lazy-du.com"]'))n.style.setProperty('visibility','hidden','important');});const hiddenBrand=await p.evaluate(()=>[...document.querySelectorAll('.brand,footer a[href*="lazy-du.com"]')].every(n=>getComputedStyle(n).visibility==='hidden'));assert.equal(hiddenBrand,true,'Brand is actually hidden in computed styles');await shot(p,'signature-logo-hidden-en-375.png');await p.evaluate(()=>{for(const n of document.querySelectorAll('.brand,footer a[href*="lazy-du.com"]'))n.style.removeProperty('visibility');});add({name:'Signature capture',brandAndFooterHidden:true,computedVisibilityChecked:true,charactersRetained:true});
  const cdp=await context.newCDPSession(p);await cdp.send('Tracing.start',{categories:'devtools.timeline,disabled-by-default-devtools.timeline.frame',transferMode:'ReturnAsStream'});const interaction=[];
  const measure=async(name,click,selector)=>{await click();await p.locator(selector).waitFor({state:'visible'});const running=await p.evaluate(()=>document.getAnimations().map(a=>({type:a.constructor.name,state:a.playState,durationMs:a.effect?.getTiming().duration})));await settled(p);const finish=await p.evaluate(()=>({atMs:performance.now(),input:window.publicProbe.inputs.at(-1)}));interaction.push({name,unit:'milliseconds',clickToSettledFrameMs:finish.atMs-finish.input.inputAtMs,clickToNextRafMs:finish.input.nextFrameAtMs-finish.input.inputAtMs,animations:running});};
  for(let n=0;n<3;n++){await measure('Team tab',()=>p.click('#tab-team'),'#view-team');await p.click('#tab-home');await measure('WEN overview',()=>p.click('#clean-wen'),'#drawer');await p.keyboard.press('Escape');await measure('Example decision',()=>p.click('#waiting-open'),'#drawer');await p.keyboard.press('Escape');}
  const values=interaction.map(x=>x.clickToSettledFrameMs).sort((a,b)=>a-b),quantile=q=>values[Math.min(values.length-1,Math.ceil(q*values.length)-1)];add({name:'Three real interactions',scope:'Laboratory, trusted Playwright clicks and requestAnimationFrame timestamps; not a 60 fps video',samples:interaction,medianMs:quantile(.5),p99Ms:quantile(.99)});
  await p.goto(base+'/?lang=en');await p.locator('#welcome').waitFor({state:'visible'});await p.getByRole('button',{name:'Just me',exact:true}).click();await p.getByRole('button',{name:'My next step',exact:true}).click();await p.waitForFunction(()=>document.querySelector('#clean-source').textContent==='Local reading');await settled(p);await p.evaluate(()=>{window.publicProbe.frames=[];window.publicProbe.shifts=[];});const stableStart=await p.evaluate(()=>performance.now());await p.waitForTimeout(60000);const stability=await p.evaluate(start=>({elapsedMs:performance.now()-start,frames:window.publicProbe.frames,shifts:window.publicProbe.shifts,data:window.PanelClean.status()}),stableStart);const gaps=stability.frames.slice(1).map((t,i)=>t-stability.frames[i]).sort((a,b)=>a-b);add({name:'60 second stable synthetic profile',scope:'Laboratory rAF cadence and layout shifts; no new fixture lines',elapsedMs:stability.elapsedMs,observedRafCallbacks:stability.frames.length,medianRafIntervalMs:gaps[Math.floor(gaps.length/2)],p99RafIntervalMs:gaps[Math.min(gaps.length-1,Math.ceil(gaps.length*.99)-1)],shifts:stability.shifts,cls:stability.shifts.reduce((a,b)=>a+b.value,0),data:stability.data});assert.equal(stability.shifts.length,0,'Stable synthetic profile does not shift for 60 seconds');
  const complete=new Promise(r=>cdp.once('Tracing.tracingComplete',r));await cdp.send('Tracing.end');const {stream}=await complete;let trace='';for(;;){const chunk=await cdp.send('IO.read',{handle:stream});trace+=chunk.base64Encoded?Buffer.from(chunk.data,'base64').toString():chunk.data;if(chunk.eof)break;}await cdp.send('IO.close',{handle:stream});fs.writeFileSync(path.join(out,'interaction-and-stability.trace.json'),trace);add({name:'CDP timeline',artifact:'interaction-and-stability.trace.json',format:'Chrome trace JSON',scope:'Three real interactions and 60 second stable synthetic profile',unit:'Trace timestamps in microseconds; summaries in milliseconds'});
  add({name:'Initial network transfer',scope:'Local laboratory; encoded Content-Length versus decoded response bytes',resources:initialWire,decodedBytes:initialWire.reduce((n,x)=>n+x.decodedBytes,0),wireBytes:initialWire.reduce((n,x)=>n+(x.wireBytes||0),0),textCompression:initialWire.filter(x=>/javascript|text|svg|json/.test(x.type)&&x.decodedBytes>1024).every(x=>x.encoding==='gzip')});await context.close();
  const sound=await browser.newContext({viewport:{width:390,height:1000}}),sp=await sound.newPage(),external=[];sp.on('request',r=>{if(new URL(r.url()).origin!==base)external.push(new URL(r.url()).origin);});await sound.addInitScript(()=>{window.providerCommands=[];window.mediaPlayCalls=0;const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(...args){window.mediaPlayCalls++;return play.apply(this,args);};addEventListener('message',e=>{if(e.origin==='https://www.youtube-nocookie.com'){try{const d=JSON.parse(e.data);if(d.event==='fixtureCommand')window.providerCommands.push(d.func);}catch{}}});});
  await sp.route('https://www.youtube-nocookie.com/**',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><p>Fictional provider fixture. No audio stream.</p><script>addEventListener("message",e=>{try{const d=JSON.parse(e.data);if(d.event==="command")parent.postMessage(JSON.stringify({event:"fixtureCommand",func:d.func}),"*");}catch{}});parent.postMessage(JSON.stringify({event:"onReady"}),"*");</script>'}));
  await sp.goto(base+'/?example=1&size=large&lang=en');await sp.waitForSelector('#home-stage .du-agent');assert.equal(await sp.locator('iframe').count(),0,'No player exists before a gesture');assert.deepEqual(external,[],'No external provider request before a gesture');assert.equal(await sp.evaluate(()=>window.mediaPlayCalls),0,'No native media play before a gesture');const initial=await sp.evaluate(()=>window.DuLofi.instance.getState());assert.equal(initial.muted,true);assert.equal(initial.volume,15);
  await sp.click('.clean-more > summary');await sp.getByRole('button',{name:'Preferences',exact:true}).click();await sp.locator('[data-control="lofi-trigger"]').click();await sp.click('#close-drawer');await sp.waitForFunction(()=>window.DuLofi.instance.getState().ready);await sp.getByRole('button',{name:'Sound on',exact:true}).click();assert.equal(await sp.evaluate(()=>window.DuLofi.instance.getState().muted),false);await sp.getByRole('button',{name:'Mute',exact:true}).click();assert.equal(await sp.evaluate(()=>window.DuLofi.instance.getState().muted),true);const commands=await sp.evaluate(()=>window.providerCommands);await shot(sp,'sound-muted-provider-fixture-en-390.png');await sp.reload();await sp.waitForSelector('#home-stage .du-agent');assert.equal(await sp.evaluate(()=>window.DuLofi.instance.getState().muted),true,'Mute persists across reload in the same tab');assert.equal(await sp.locator('iframe').count(),0,'Reload never autostarts the provider');add({name:'Sound controller',scope:'Deterministic provider fixture, no third-party acoustic measurement',noProviderBeforeGesture:true,noNativePlayBeforeGesture:true,initialVolume:15,initialMuted:true,unmuteAndMute:true,mutePersistsAcrossReload:true,noAutostartAfterReload:true,commands});await sound.close();return {captures,checks};
}
module.exports={runFocused};
