'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
async function checkAccess({browser,base,out}){
  const results=[],errors=[],sample=await(await fetch(base+'/api/status?example=1&size=large')).json();
  const save=()=>fs.writeFileSync(path.join(out,'access-validation.json'),JSON.stringify({ok:!errors.length,scope:'Visible public controls and text, fictional examples and synthetic metadata; measurements in CSS pixels',results,errors},null,2)+'\n');
  for(const locale of ['en','pt','es'])for(const width of [375,768,1440]){
    const context=await browser.newContext({viewport:{width,height:width===375?812:width===1440?900:1000}}),page=await context.newPage(),events=[];
    page.on('pageerror',e=>events.push({type:'JavaScript',message:e.message}));page.on('console',m=>{if(m.type()==='error')events.push({type:'console',message:m.text()});});page.on('requestfailed',r=>events.push({type:'request failed',url:new URL(r.url()).pathname}));page.on('response',r=>{if(r.status()>=400)events.push({type:'HTTP',status:r.status(),url:new URL(r.url()).pathname});});
    await page.addInitScript(()=>localStorage.setItem('agent-panel-profile',JSON.stringify({version:2,mode:'explorer',size:'large',goal:'finish'})));
    const key=locale+'-'+width;
    try{
      await page.goto(base+'/?example=1&size=large&lang='+locale);await page.waitForFunction(()=>document.body.dataset.panelMounted==='true');await page.waitForTimeout(150);
      async function inspect(state){
        await page.waitForTimeout(200);const report=await page.evaluate(()=>{
          const shown=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility==='visible'&&!e.closest('[hidden]')&&(!e.closest('dialog')||e.closest('dialog').open);};
          const color=s=>{const a=s.match(/[\d.]+/g)?.map(Number)||[0,0,0];return [a[0],a[1],a[2],a[3]??1];},blend=(a,b)=>a.slice(0,3).map((v,i)=>v*a[3]+b[i]*(1-a[3])),bg=e=>{let p=e,b=[8,8,9];const chain=[];while(p){chain.unshift(p);p=p.parentElement;}for(const n of chain)b=blend(color(getComputedStyle(n).backgroundColor),b);return b;},lum=a=>a.slice(0,3).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0),ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05),name=e=>e.id||e.className?.toString()||e.tagName;
          const controls=[...document.querySelectorAll('button,a[href],summary,input,select,textarea,[role=button]')].filter(shown).map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {id:name(e),role:e.getAttribute('role')||e.tagName.toLowerCase(),name:e.getAttribute('aria-label')||e.textContent.trim().slice(0,90),width:r.width,height:r.height,fontSize:parseFloat(s.fontSize),disabled:!!e.disabled};});
          const contrast=[...document.querySelectorAll('body *')].filter(e=>shown(e)&&[...e.childNodes].some(n=>n.nodeType===3&&n.textContent.trim())).map(e=>{const s=getComputedStyle(e),b=bg(e),f=blend(color(s.color),b),size=parseFloat(s.fontSize),large=size>=24||size>=18.66&&Number(s.fontWeight)>=700,disabled=!!e.disabled||!!e.closest('[disabled]'),gradient=[e,...function*(n){while(n.parentElement){n=n.parentElement;yield n;}}(e)].some(n=>getComputedStyle(n).backgroundImage!=='none');return{id:name(e),text:e.textContent.trim().slice(0,80),fontSize:size,ratio:ratio(f,b),required:large?3:4.5,disabled,gradient};});
          const tablist=document.querySelector('[role=tablist]'),tabs=[...document.querySelectorAll('[role=tab]')].map(e=>({id:e.id,insideTablist:tablist.contains(e),selected:e.getAttribute('aria-selected'),name:e.textContent}));
          const f=document.activeElement,fs=getComputedStyle(f);return {focus:{id:name(f),outline:fs.outlineStyle,width:fs.outlineWidth,ratio:ratio(color(fs.outlineColor),bg(f.parentElement||f))},overflow:document.documentElement.scrollWidth>innerWidth,controls,contrast,tabs,source:document.querySelector('#clean-source').textContent};
        });
        report.contrast=await page.evaluate(require('./validate-controls.cjs').measureContrast);results.push({locale,width,state,...report});const verify=(ok,message)=>{if(!ok)errors.push({scenario:key+' '+state,message});};verify(!report.overflow,'No lateral scrolling');for(const c of report.controls)verify(c.width>=43.9&&c.height>=43.9,'Clickable target '+c.id+' '+c.width+'×'+c.height);for(const c of report.controls.filter(c=>/input|textarea|select/.test(c.role)))if(width<600)verify(c.fontSize>=16,'Mobile field '+c.id+' '+c.fontSize+'px');verify(report.tabs.length===4,'Four public tabs');verify(report.tabs.every(t=>t.insideTablist),'Tabs retain tablist context');for(const c of report.contrast){verify(c.backgroundResolved,'Effective background resolved '+c.id);if(!c.disabled&&c.backgroundResolved)verify(c.ratio>=c.required-.02,'Contrast '+c.id+' '+c.ratio.toFixed(3)+' '+c.text);}
      }
      await inspect('Home');await page.screenshot({path:path.join(out,'home-'+key+'.png'),fullPage:true});await page.screenshot({path:path.join(out,'home-first-fold-'+key+'.png'),fullPage:false});
      await page.locator('#clean-wen').click();await inspect('WEN');assert.equal(await page.locator('#drawer .wen-lines>div').count(),6,key+' WEN has six labelled lines');await page.screenshot({path:path.join(out,'wen-'+key+'.png'),fullPage:true});await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'close-drawer',key+' WEN Tab retains focus');await inspect('WEN keyboard focus');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'clean-wen',key+' Escape returns focus');
      await page.locator('.clean-more>summary').click();await page.locator('.clean-menu>button:not([data-view])').click();await inspect('Preferences');await page.screenshot({path:path.join(out,'preferences-'+key+'.png'),fullPage:true});await page.keyboard.press('Escape');
      await page.locator('#clean-auto').click();await inspect('Automatic routine');await page.screenshot({path:path.join(out,'routine-'+key+'.png'),fullPage:true});await page.keyboard.press('Escape');
      await page.locator('#tab-team').click();await inspect('Team');await page.screenshot({path:path.join(out,'team-'+key+'.png'),fullPage:true});const signature=await page.evaluate(()=>{const nodes=[...document.querySelectorAll('.brand,footer a[href*="lazy-du.com"]')];for(const e of nodes)e.style.setProperty('visibility','hidden','important');return {brandingHidden:nodes.every(e=>getComputedStyle(e).visibility==='hidden'),portraits:document.querySelectorAll('#team-stage .du-art img').length};});assert(signature.brandingHidden&&signature.portraits>0,key+' masked Team retains Du');results.push({locale,width,state:'Team signature without brand',...signature});await page.screenshot({path:path.join(out,'team-signature-masked-'+key+'.png'),fullPage:false});await page.screenshot({path:path.join(out,'team-signature-masked-full-'+key+'.png'),fullPage:true});const oldBrand=await page.evaluate(()=>{const brand=document.querySelector('header .brand'),span=brand.querySelector('span'),old=span.innerHTML;brand.style.setProperty('visibility','visible','important');brand.querySelector('img').style.setProperty('visibility','hidden','important');span.textContent='Linear';return old;});await page.screenshot({path:path.join(out,'team-signature-counterfactual-'+key+'.png'),fullPage:false});await page.evaluate(old=>{const brand=document.querySelector('header .brand');brand.querySelector('span').innerHTML=old;brand.querySelector('img').style.removeProperty('visibility');brand.style.removeProperty('visibility');for(const e of document.querySelectorAll('footer a[href*="lazy-du.com"]'))e.style.removeProperty('visibility');},oldBrand);await page.locator('#tab-home').click();
      const hidden=await page.evaluate(()=>{const nodes=[...document.querySelectorAll('.brand,footer a[href*="lazy-du.com"]')];for(const e of nodes)e.style.setProperty('visibility','hidden','important');return {brandingHidden:nodes.every(e=>getComputedStyle(e).visibility==='hidden'),portraits:document.querySelectorAll('#home-stage .du-art img').length};});assert(hidden.brandingHidden&&hidden.portraits>0,key+' brand hidden, character signature retained');results.push({locale,width,state:'Signature without branding',...hidden});await page.screenshot({path:path.join(out,'signature-logo-hidden-'+key+'.png'),fullPage:true});await page.screenshot({path:path.join(out,'signature-first-fold-'+key+'.png'),fullPage:false});
      assert.equal(events.length,0,key+' no browser errors');
    }catch(e){errors.push({scenario:key,message:e.message,stack:e.stack});}finally{await context.close();save();}
  }
  for(const locale of ['en','pt']){const context=await browser.newContext({viewport:{width:390,height:1100}}),page=await context.newPage();await page.addInitScript(()=>localStorage.setItem('agent-panel-profile',JSON.stringify({version:2,mode:'explorer',size:'large',goal:'finish'})));await page.goto(base+'/?example=1&size=large&lang='+locale);await page.waitForFunction(()=>document.body.dataset.panelMounted==='true');await page.screenshot({path:path.join(out,'home-'+locale+'-390.png'),fullPage:true});await context.close();}
  // A one-session synthetic metadata response tests grammar and unknown tasks without conversation content.
  for(const locale of ['en','pt','es']){const context=await browser.newContext({viewport:{width:375,height:1100}}),page=await context.newPage();await page.addInitScript(()=>localStorage.setItem('agent-panel-profile',JSON.stringify({version:2,mode:'beginner',size:'solo',goal:'finish'})));const synthetic=structuredClone(sample);synthetic.example=false;synthetic.tasks=[];synthetic.cards=[];synthetic.board={connected:false};synthetic.usage.ready=true;synthetic.usage.errors=0;synthetic.usage.updated=new Date().toISOString();synthetic.usage.sessions=synthetic.usage.sessions.slice(0,1);synthetic.usage.sessions[0].state='recent';delete synthetic.usage.sessions[0].title;delete synthetic.usage.sessions[0].titlePT;delete synthetic.usage.sessions[0].titleES;await page.route('**/api/status*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(synthetic)}));try{await page.goto(base+'/?lang='+locale);await page.waitForFunction(()=>document.body.dataset.panelMounted==='true');const label=await page.locator('#v21-count span').textContent();assert.equal(label,{en:'session with recent activity',pt:'sessão com atividade recente',es:'sesión con actividad reciente'}[locale],locale+' singular session');await page.locator('#clean-active').click();const text=await page.locator('#drawer-body').textContent();assert(/UTC/.test(text),locale+' source exposes reading time');await page.screenshot({path:path.join(out,'metadata-source-'+locale+'-375.png'),fullPage:true});results.push({locale,width:375,state:'Synthetic metadata source',label,source:text,ok:true});}catch(e){errors.push({scenario:'Synthetic '+locale,message:e.message,stack:e.stack});}finally{await context.close();save();}}
  save();return {ok:!errors.length,results,errors};
}
module.exports={checkAccess};
